namespace FoxyBalance.CLI.Domain

open System
open Thoth.Json.Core
open FoxyBalance.CLI

/// Thoth-based JSON encoders and decoders for CLI domain types.
/// Uses reflection-free JsonHelpers (Utf8JsonWriter + JsonDocument.Parse) instead of
/// Thoth.Json.System.Text.Json (which depends on reflection-based JsonSerializer, broken by PublishTrimmed).
module Codecs =


    // ---- HAL Link ----

    let halLinkEncoder (link: HalLink) : IEncodable =
        Encode.object [
            "href", Encode.string link.Href
            match link.Method with
            | Some m -> "method", Encode.string m
            | None -> ()
            match link.Templated with
            | Some t -> "templated", Encode.bool t
            | None -> ()
        ]

    let halLinkDecoder : Decoder<HalLink> =
        Decode.object (fun get ->
            { Href = get.Required.Field "href" Decode.string
              Method = get.Optional.Field "method" Decode.string
              Templated = get.Optional.Field "templated" Decode.bool })

    let halLinksEncoder (links: Map<string, HalLink>) : IEncodable =
        links
        |> Map.toList
        |> List.map (fun (rel, link) -> rel, halLinkEncoder link)
        |> Encode.object

    let halLinksDecoder : Decoder<Map<string, HalLink>> =
        Decode.dict halLinkDecoder

    let halLinksOptionEncoder (links: Map<string, HalLink> option) : IEncodable =
        match links with
        | Some l -> halLinksEncoder l
        | None -> Encode.nil

    let halLinksOptionDecoder : Decoder<Map<string, HalLink> option> =
        Decode.oneOf [
            halLinksDecoder |> Decode.map Some
            Decode.nil None
        ]

    // ---- HAL Resource ----

    let halResourceEncoder (dataEncoder: Encoder<'T>) (resource: HalResource<'T>) : IEncodable =
        Encode.object [
            "data", dataEncoder resource.Data
            "links", halLinksOptionEncoder resource.Links
            "embedded",
                match resource.Embedded with
                | Some _ -> Encode.nil
                | None -> Encode.nil
        ]

    let halResourceDecoder (dataDecoder: Decoder<'T>) : Decoder<HalResource<'T>> =
        Decode.object (fun get ->
            { Data = get.Required.Field "data" dataDecoder
              Links = get.Optional.Field "links" halLinksDecoder
              Embedded = None })

    // ---- HAL Collection ----

    let halCollectionEncoder (dataEncoder: Encoder<'T>) (collection: HalCollection<'T>) : IEncodable =
        Encode.object [
            "items", collection.Items |> List.map (halResourceEncoder dataEncoder) |> Encode.list
            "page", Encode.int collection.Page
            "totalPages", Encode.int collection.TotalPages
            "totalCount", Encode.int collection.TotalCount
            "links", halLinksOptionEncoder collection.Links
        ]

    let halCollectionDecoder (dataDecoder: Decoder<'T>) : Decoder<HalCollection<'T>> =
        Decode.object (fun get ->
            { Items = get.Required.Field "items" (Decode.list (halResourceDecoder dataDecoder))
              Page = get.Required.Field "page" Decode.int
              TotalPages = get.Required.Field "totalPages" Decode.int
              TotalCount = get.Required.Field "totalCount" Decode.int
              Links = get.Optional.Field "links" halLinksDecoder })

    // ---- DTO Decoders ----

    let tokenResponseDecoder : Decoder<TokenResponse> =
        Decode.object (fun get ->
            { AccessToken = get.Required.Field "accessToken" Decode.string
              RefreshToken = get.Required.Field "refreshToken" Decode.string
              ExpiresIn = get.Required.Field "expiresIn" Decode.int
              TokenType = get.Required.Field "tokenType" Decode.string })

    let apiErrorDecoder : Decoder<ApiError> =
        Decode.object (fun get ->
            { Error = get.Required.Field "error" Decode.string
              Details = get.Optional.Field "details" (Decode.list Decode.string) })

    let transactionDtoDecoder : Decoder<TransactionDto> =
        Decode.object (fun get ->
            { Id = get.Required.Field "id" Decode.int64
              Name = get.Required.Field "name" Decode.string
              Amount = get.Required.Field "amount" Decode.decimal
              DateCreated = get.Required.Field "dateCreated" Decode.datetimeOffset
              Type = get.Required.Field "type" Decode.string
              Status = get.Required.Field "status" Decode.string
              ClearDate = get.Optional.Field "clearDate" Decode.datetimeOffset
              RecurringBillId = get.Optional.Field "recurringBillId" Decode.int64
              AutoGenerated = get.Optional.Field "autoGenerated" Decode.bool |> Option.defaultValue false
              ImportId = get.Optional.Field "importId" Decode.string })

    let recurringBillDtoDecoder : Decoder<RecurringBillDto> =
        Decode.object (fun get ->
            { Id = get.Required.Field "id" Decode.int64
              Name = get.Required.Field "name" Decode.string
              Amount = get.Required.Field "amount" Decode.decimal
              WeekOfMonth = get.Required.Field "weekOfMonth" Decode.int
              DayOfWeek = get.Required.Field "dayOfWeek" Decode.int
              DateCreated = get.Required.Field "dateCreated" Decode.datetimeOffset
              LastAppliedDate = get.Optional.Field "lastAppliedDate" Decode.datetimeOffset
              Active = get.Required.Field "active" Decode.bool })

    let transactionSumDecoder : Decoder<TransactionSum> =
        Decode.object (fun get ->
            { Sum = get.Required.Field "sum" Decode.decimal
              PendingSum = get.Required.Field "pendingSum" Decode.decimal
              ClearedSum = get.Required.Field "clearedSum" Decode.decimal
              PendingDebitSum = get.Required.Field "pendingDebitSum" Decode.decimal
              ClearedDebitSum = get.Required.Field "clearedDebitSum" Decode.decimal
              PendingCreditSum = get.Required.Field "pendingCreditSum" Decode.decimal
              ClearedCreditSum = get.Required.Field "clearedCreditSum" Decode.decimal })

    let matchSuggestionDtoDecoder : Decoder<MatchSuggestionDto> =
        Decode.object (fun get ->
            { Transaction = get.Required.Field "transaction" transactionDtoDecoder
              RecurringBill = get.Required.Field "recurringBill" recurringBillDtoDecoder
              MatchScore = get.Required.Field "matchScore" Decode.decimal })

    let importResultDtoDecoder : Decoder<ImportResultDto> =
        Decode.object (fun get ->
            { ImportedCount = get.Required.Field "importedCount" Decode.int
              TotalCount = get.Required.Field "totalCount" Decode.int
              SkippedCount = get.Required.Field "skippedCount" Decode.int })

    // ---- DTO Encoders ----

    let tokenResponseEncoder (t: TokenResponse) : IEncodable =
        Encode.object [
            "accessToken", Encode.string t.AccessToken
            "refreshToken", Encode.string t.RefreshToken
            "expiresIn", Encode.int t.ExpiresIn
            "tokenType", Encode.string t.TokenType
        ]

    let transactionDtoEncoder (t: TransactionDto) : IEncodable =
        Encode.object [
            "id", Encode.int64 t.Id
            "name", Encode.string t.Name
            "amount", Encode.decimal t.Amount
            "dateCreated", Encode.datetimeOffset t.DateCreated
            "type", Encode.string t.Type
            "status", Encode.string t.Status
            match t.ClearDate with
            | Some d -> "clearDate", Encode.datetimeOffset d
            | None -> ()
            match t.RecurringBillId with
            | Some id -> "recurringBillId", Encode.int64 id
            | None -> ()
            "autoGenerated", Encode.bool t.AutoGenerated
            match t.ImportId with
            | Some id -> "importId", Encode.string id
            | None -> ()
        ]

    let recurringBillDtoEncoder (b: RecurringBillDto) : IEncodable =
        Encode.object [
            "id", Encode.int64 b.Id
            "name", Encode.string b.Name
            "amount", Encode.decimal b.Amount
            "weekOfMonth", Encode.int b.WeekOfMonth
            "dayOfWeek", Encode.int b.DayOfWeek
            "dateCreated", Encode.datetimeOffset b.DateCreated
            match b.LastAppliedDate with
            | Some d -> "lastAppliedDate", Encode.datetimeOffset d
            | None -> ()
            "active", Encode.bool b.Active
        ]

    let transactionSumEncoder (s: TransactionSum) : IEncodable =
        Encode.object [
            "sum", Encode.decimal s.Sum
            "pendingSum", Encode.decimal s.PendingSum
            "clearedSum", Encode.decimal s.ClearedSum
            "pendingDebitSum", Encode.decimal s.PendingDebitSum
            "clearedDebitSum", Encode.decimal s.ClearedDebitSum
            "pendingCreditSum", Encode.decimal s.PendingCreditSum
            "clearedCreditSum", Encode.decimal s.ClearedCreditSum
        ]

    let matchSuggestionDtoEncoder (s: MatchSuggestionDto) : IEncodable =
        Encode.object [
            "transaction", transactionDtoEncoder s.Transaction
            "recurringBill", recurringBillDtoEncoder s.RecurringBill
            "matchScore", Encode.decimal s.MatchScore
        ]

    let importResultDtoEncoder (r: ImportResultDto) : IEncodable =
        Encode.object [
            "importedCount", Encode.int r.ImportedCount
            "totalCount", Encode.int r.TotalCount
            "skippedCount", Encode.int r.SkippedCount
        ]

    // ---- Request Encoders ----

    let tokenExchangeRequestEncoder (r: TokenExchangeRequest) : IEncodable =
        Encode.object [
            "apiKey", Encode.string r.ApiKey
            "apiSecret", Encode.string r.ApiSecret
        ]

    let tokenRefreshRequestEncoder (r: TokenRefreshRequest) : IEncodable =
        Encode.object [
            "refreshToken", Encode.string r.RefreshToken
        ]

    let apiTransactionRequestEncoder (r: ApiTransactionRequest) : IEncodable =
        Encode.object [
            "name", Encode.string r.Name
            "amount", Encode.string r.Amount
            "date", Encode.string r.Date
            "clearDate", Encode.string r.ClearDate
            "transactionType", Encode.string r.TransactionType
            "checkNumber", Encode.string r.CheckNumber
        ]

    let apiRecurringBillRequestEncoder (r: ApiRecurringBillRequest) : IEncodable =
        Encode.object [
            "name", Encode.string r.Name
            "amount", Encode.string r.Amount
            "weekOfMonth", Encode.string r.WeekOfMonth
            "dayOfWeek", Encode.string r.DayOfWeek
        ]

    let apiMatchRequestEncoder (r: ApiMatchRequest) : IEncodable =
        Encode.object [
            "transactionId", Encode.int64 r.TransactionId
            "billId", Encode.int64 r.BillId
        ]

    let apiBulkImportRequestEncoder (r: ApiBulkImportRequest) : IEncodable =
        Encode.object [
            "format", Encode.string r.Format
            "transactions", Encode.string r.Transactions
        ]

    // ---- Serialize / Deserialize Helpers ----

    let serialize (encoder: Encoder<'T>) (value: 'T) : string =
        JsonHelpers.encodeToString 0 (encoder value)

    let serializeIndented (encoder: Encoder<'T>) (value: 'T) : string =
        JsonHelpers.encodeToString 2 (encoder value)

    let deserialize (decoder: Decoder<'T>) (json: string) : Result<'T, string> =
        JsonHelpers.decodeFromString decoder json

    // ---- HAL Resource Helpers ----

    let deserializeHalResource (dataDecoder: Decoder<'T>) (json: string) : Result<HalResource<'T>, string> =
        JsonHelpers.decodeFromString (halResourceDecoder dataDecoder) json

    let deserializeHalCollection (dataDecoder: Decoder<'T>) (json: string) : Result<HalCollection<'T>, string> =
        JsonHelpers.decodeFromString (halCollectionDecoder dataDecoder) json

    let deserializeData (dataDecoder: Decoder<'T>) (json: string) : Result<'T, string> =
        JsonHelpers.decodeFromString dataDecoder json
        |> Result.bind (fun data ->
            // The API wraps data in a HAL resource: { "data": {...}, ... }
            // But if we got a direct object, use it
            Ok data)

    /// Deserialize the `data` field from a HAL response, discarding links.
    let extractData (dataDecoder: Decoder<'T>) (json: string) : Result<'T, string> =
        // Try decoding as HAL resource first, extract .Data
        let halResult = JsonHelpers.decodeFromString (halResourceDecoder dataDecoder) json
        match halResult with
        | Ok hal -> Ok hal.Data
        | Error _ ->
            // Fall back to direct decode (for non-HAL responses)
            JsonHelpers.decodeFromString dataDecoder json

    // ---- Typed HAL Resource Serializers (for --json output) ----

    let serializeHalResource (dataEncoder: Encoder<'T>) (resource: HalResource<'T>) : string =
        JsonHelpers.encodeToString 2 (halResourceEncoder dataEncoder resource)

    let serializeHalCollection (dataEncoder: Encoder<'T>) (collection: HalCollection<'T>) : string =
        JsonHelpers.encodeToString 2 (halCollectionEncoder dataEncoder collection)
