namespace FoxyBalance.CLI.Domain

open System
open System.Text.Json
open System.Text.Json.Serialization

// ---- API Request Types (mirrors FoxyBalance.Server.API.Models.Requests) ----

[<CLIMutable>]
type TokenExchangeRequest =
    { ApiKey: string
      ApiSecret: string }

[<CLIMutable>]
type TokenRefreshRequest =
    { RefreshToken: string }

[<CLIMutable>]
type ApiTransactionRequest =
    { Name: string
      Amount: string
      Date: string
      ClearDate: string
      TransactionType: string
      CheckNumber: string }

[<CLIMutable>]
type ApiRecurringBillRequest =
    { Name: string
      Amount: string
      WeekOfMonth: string
      DayOfWeek: string }

[<CLIMutable>]
type ApiMatchRequest =
    { TransactionId: int64
      BillId: int64 }

[<CLIMutable>]
type ApiBulkImportRequest =
    { Format: string
      Transactions: string }

// ---- API Response Types ----

[<CLIMutable>]
type TokenResponse =
    { AccessToken: string
      RefreshToken: string
      ExpiresIn: int
      TokenType: string }

[<CLIMutable>]
type ApiError =
    { Error: string
      Details: string list option }

[<CLIMutable>]
type TransactionDto =
    { Id: int64
      Name: string
      Amount: decimal
      DateCreated: DateTimeOffset
      Type: string
      Status: string
      ClearDate: DateTimeOffset option
      RecurringBillId: int64 option
      AutoGenerated: bool
      ImportId: string option }

[<CLIMutable>]
type RecurringBillDto =
    { Id: int64
      Name: string
      Amount: decimal
      WeekOfMonth: int
      DayOfWeek: int
      DateCreated: DateTimeOffset
      LastAppliedDate: DateTimeOffset option
      Active: bool }

[<CLIMutable>]
type TransactionSum =
    { Sum: decimal
      PendingSum: decimal
      ClearedSum: decimal
      PendingDebitSum: decimal
      ClearedDebitSum: decimal
      PendingCreditSum: decimal
      ClearedCreditSum: decimal }

[<CLIMutable>]
type MatchSuggestionDto =
    { Transaction: TransactionDto
      RecurringBill: RecurringBillDto
      MatchScore: decimal }

[<CLIMutable>]
type ImportResultDto =
    { ImportedCount: int
      TotalCount: int
      SkippedCount: int }

// ---- HAL Wrapper Types (for deserialization) ----

[<CLIMutable>]
type HalLink =
    { [<JsonPropertyName("href")>]
      Href: string
      [<JsonPropertyName("method")>]
      Method: string option
      [<JsonPropertyName("templated")>]
      Templated: bool option }

[<CLIMutable>]
type HalResource<'T> =
    { [<JsonPropertyName("data")>]
      Data: 'T
      [<JsonPropertyName("links")>]
      Links: Map<string, HalLink> option
      [<JsonPropertyName("embedded")>]
      Embedded: obj option }

[<CLIMutable>]
type HalCollection<'T> =
    { [<JsonPropertyName("items")>]
      Items: HalResource<'T> list
      [<JsonPropertyName("page")>]
      Page: int
      [<JsonPropertyName("totalPages")>]
      TotalPages: int
      [<JsonPropertyName("totalCount")>]
      TotalCount: int
      [<JsonPropertyName("links")>]
      Links: Map<string, HalLink> option }

module JsonSerializerOptions =
    let defaults =
        let opts = JsonSerializerOptions()
        opts.PropertyNameCaseInsensitive <- true
        opts.PropertyNamingPolicy <- JsonNamingPolicy.CamelCase
        opts
