namespace FoxyBalance.CLI.Domain

open System

// ---- API Request Types (mirrors FoxyBalance.Server.API.Models.Requests) ----

[<CLIMutable>]
type TokenExchangeRequest =
    { ApiKey: string
      ApiSecret: string }

[<CLIMutable>]
type TokenRefreshRequest =
    { RefreshToken: string }

[<CLIMutable>]
type ApiTransactionRequest =
    { Name: string
      Amount: string
      Date: string
      ClearDate: string
      TransactionType: string
      CheckNumber: string }

[<CLIMutable>]
type ApiRecurringBillRequest =
    { Name: string
      Amount: string
      WeekOfMonth: string
      DayOfWeek: string }

[<CLIMutable>]
type ApiMatchRequest =
    { TransactionId: int64
      BillId: int64 }

[<CLIMutable>]
type ApiBulkImportRequest =
    { Format: string
      Transactions: string }

// ---- API Response Types ----

[<CLIMutable>]
type TokenResponse =
    { AccessToken: string
      RefreshToken: string
      ExpiresIn: int
      TokenType: string }

[<CLIMutable>]
type ApiError =
    { Error: string
      Details: string list option }

[<CLIMutable>]
type TransactionDto =
    { Id: int64
      Name: string
      Amount: decimal
      DateCreated: DateTimeOffset
      Type: string
      Status: string
      ClearDate: DateTimeOffset option
      RecurringBillId: int64 option
      AutoGenerated: bool
      ImportId: string option }

[<CLIMutable>]
type RecurringBillDto =
    { Id: int64
      Name: string
      Amount: decimal
      WeekOfMonth: int
      DayOfWeek: int
      DateCreated: DateTimeOffset
      LastAppliedDate: DateTimeOffset option
      Active: bool }

[<CLIMutable>]
type TransactionSum =
    { Sum: decimal
      PendingSum: decimal
      ClearedSum: decimal
      PendingDebitSum: decimal
      ClearedDebitSum: decimal
      PendingCreditSum: decimal
      ClearedCreditSum: decimal }

[<CLIMutable>]
type MatchSuggestionDto =
    { Transaction: TransactionDto
      RecurringBill: RecurringBillDto
      MatchScore: decimal }

[<CLIMutable>]
type ImportResultDto =
    { ImportedCount: int
      TotalCount: int
      SkippedCount: int }

// ---- HAL Wrapper Types (for deserialization) ----

type HalLink =
    { Href: string
      Method: string option
      Templated: bool option }

type HalResource<'T> =
    { Data: 'T
      Links: Map<string, HalLink> option
      Embedded: obj option }

type HalCollection<'T> =
    { Items: HalResource<'T> list
      Page: int
      TotalPages: int
      TotalCount: int
      Links: Map<string, HalLink> option }


// ---- Link Resolution Helpers ----

/// Resolve an ID argument that may be either a numeric ID or a HATEOAS link href.
/// Returns the API path to use for the request.
/// For numeric IDs, builds the path from the basePath template.
/// For link hrefs (paths like /api/v1/transactions/123), uses them directly.
module LinkResolver =
    /// Try to parse a string as a numeric int64 ID.
    let tryParseId (s: string) : int64 option =
        match System.Int64.TryParse(s) with
        | true, v -> Some v
        | _ -> None

    /// Check if a string looks like a HATEOAS link (starts with /api/ or http).
    let isLinkHref (s: string) : bool =
        s.StartsWith("/api/", StringComparison.OrdinalIgnoreCase)
        || s.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
        || s.StartsWith("https://", StringComparison.OrdinalIgnoreCase)

    /// Resolve an ID argument to an API path.
    /// If the argument is a numeric ID, builds {basePath}/{id}.
    /// If the argument is a link href, uses it directly (stripping any query string).
    let resolvePath (basePath: string) (idOrLink: string) : string =
        if isLinkHref idOrLink then
            // Strip query string for single-resource links
            let href = idOrLink.Split('?').[0]
            // If it's a full URL, extract just the path
            if href.StartsWith("http", StringComparison.OrdinalIgnoreCase) then
                let uri = Uri(href)
                uri.AbsolutePath
            else
                href
        else
            match tryParseId idOrLink with
            | Some id -> sprintf "%s/%d" basePath id
            | None -> sprintf "%s/%s" basePath idOrLink

    /// Extract the resource ID from a link href (e.g., "/api/v1/transactions/123" -> 123).
    let extractIdFromHref (href: string) : int64 option =
        let parts = href.TrimEnd('/').Split('/')
        match Array.tryLast parts with
        | Some last -> tryParseId last
        | None -> None

    /// Get a link from a HAL resource's links by relation name.
    /// Returns None if the link doesn't exist.
    let tryGetLink (links: Map<string, HalLink> option) (rel: string) : HalLink option =
        links |> Option.bind (fun m -> Map.tryFind rel m)
