namespace FoxyBalance.CLI

open System
open System.Text
open System.Text.Json
open System.Text.Json.Serialization
open FoxyBalance.CLI.Domain

/// Output formatting utilities for CLI display.
module Formatters =

    let private jsonOptions =
        let opts = JsonSerializerOptions(WriteIndented = true)
        opts

    let toJson (value: obj) : string =
        JsonSerializer.Serialize(value, jsonOptions)

    let printJson (value: obj) =
        printfn "%s" (toJson value)

    /// Print a HAL resource as JSON (includes data + links).
    let printHalResourceJson (resource: HalResource<'T>) =
        printfn "%s" (toJson resource)

    /// Print a HAL collection as JSON (includes items with links + collection links).
    let printHalCollectionJson (collection: HalCollection<'T>) =
        printfn "%s" (toJson collection)


    // ---- Currency formatting ----

    let formatCurrency (amount: decimal) : string =
        amount.ToString("C2")

    // ---- Date formatting ----

    let formatDate (date: DateTimeOffset) : string =
        date.ToString("yyyy-MM-dd")

    let formatDateOption (date: DateTimeOffset option) : string =
        match date with
        | Some d -> formatDate d
        | None -> "—"

    // ---- Table helpers ----

    let private padRight (width: int) (s: string) : string =
        if s.Length >= width then s.Substring(0, width)
        else s + String(' ', width - s.Length)

    let private padLeft (width: int) (s: string) : string =
        if s.Length >= width then s.Substring(0, width)
        else String(' ', width - s.Length) + s

    let printTable (headers: string list) (rows: string list list) =
        let colCount = max headers.Length (rows |> List.map List.length |> List.fold max 0 |> max 1)
        let colWidths =
            [ for i in 0 .. colCount - 1 ->
                let headerWidth = if i < headers.Length then headers.[i].Length else 0
                let maxRowWidth =
                    rows
                    |> List.map (fun r -> if i < r.Length then r.[i].Length else 0)
                    |> List.fold max 0
                max headerWidth maxRowWidth ]

        let formatRow (cells: string list) =
            cells
            |> List.mapi (fun i cell -> padRight colWidths.[i] cell)
            |> String.concat "  "

        let separator =
            colWidths |> List.map (fun w -> String('-', w)) |> String.concat "  "

        printfn "%s" (formatRow headers)
        printfn "%s" separator
        rows |> List.iter (fun r -> printfn "%s" (formatRow r))

    // ---- Balance formatting ----

    let printBalance (sum: TransactionSum) =
        printfn ""
        printfn "Balance Summary"
        printfn "================"
        printfn "  Total Balance:     %s" (formatCurrency sum.Sum)
        printfn "  Cleared Balance:   %s" (formatCurrency sum.ClearedSum)
        printfn "  Pending Balance:   %s" (formatCurrency sum.PendingSum)
        printfn ""
        printfn "  Cleared Debits:     %s" (formatCurrency sum.ClearedDebitSum)
        printfn "  Cleared Credits:   %s" (formatCurrency sum.ClearedCreditSum)
        printfn "  Pending Debits:    %s" (formatCurrency sum.PendingDebitSum)
        printfn "  Pending Credits:   %s" (formatCurrency sum.PendingCreditSum)
        printfn ""

    // ---- Transaction formatting ----

    let transactionTypeLabel (t: string) : string =
        match t with
        | "check" -> "Check"
        | "bill" -> "Bill"
        | "credit" -> "Credit"
        | "debit" -> "Debit"
        | other -> other

    let printTransactions (transactions: TransactionDto list) =
        if List.isEmpty transactions then
            printfn "No transactions found."
        else
            let rows =
                transactions
                |> List.map (fun t ->
                    [ string t.Id
                      t.Name
                      formatCurrency t.Amount
                      formatDate t.DateCreated
                      transactionTypeLabel t.Type
                      t.Status ])

            printTable
                [ "ID"; "Name"; "Amount"; "Date"; "Type"; "Status" ]
                rows

    let printTransaction (t: TransactionDto) =
        printfn ""
        printfn "Transaction #%d" t.Id
        printfn "==============" 
        printfn "  Name:        %s" t.Name
        printfn "  Amount:      %s" (formatCurrency t.Amount)
        printfn "  Date:        %s" (formatDate t.DateCreated)
        printfn "  Type:        %s" (transactionTypeLabel t.Type)
        printfn "  Status:      %s" t.Status
        match t.ClearDate with
        | Some d -> printfn "  Clear Date:  %s" (formatDate d)
        | None -> ()
        match t.ImportId with
        | Some id when not (String.IsNullOrWhiteSpace id) -> printfn "  Import ID:   %s" id
        | _ -> ()
        match t.RecurringBillId with
        | Some billId -> printfn "  Bill ID:     %d" billId
        | None -> ()
        if t.AutoGenerated then printfn "  Auto Generated: yes"
        printfn ""

    // ---- Bill formatting ----

    let dayOfWeekLabel (day: int) : string =
        match day with
        | 0 -> "Sunday"
        | 1 -> "Monday"
        | 2 -> "Tuesday"
        | 3 -> "Wednesday"
        | 4 -> "Thursday"
        | 5 -> "Friday"
        | 6 -> "Saturday"
        | _ -> string day

    let weekLabel (week: int) : string =
        match week with
        | 1 -> "1st"
        | 2 -> "2nd"
        | 3 -> "3rd"
        | 4 -> "4th"
        | _ -> string week

    let printBills (bills: RecurringBillDto list) =
        if List.isEmpty bills then
            printfn "No bills found."
        else
            let rows =
                bills
                |> List.map (fun b ->
                    [ string b.Id
                      b.Name
                      formatCurrency b.Amount
                      weekLabel b.WeekOfMonth
                      dayOfWeekLabel b.DayOfWeek
                      if b.Active then "yes" else "no" ])

            printTable
                [ "ID"; "Name"; "Amount"; "Week"; "Day"; "Active" ]
                rows

    let printBill (b: RecurringBillDto) =
        printfn ""
        printfn "Bill #%d" b.Id
        printfn "========"
        printfn "  Name:          %s" b.Name
        printfn "  Amount:        %s" (formatCurrency b.Amount)
        printfn "  Week of Month: %s" (weekLabel b.WeekOfMonth)
        printfn "  Day of Week:    %s" (dayOfWeekLabel b.DayOfWeek)
        printfn "  Active:        %s" (if b.Active then "yes" else "no")
        printfn "  Created:       %s" (formatDate b.DateCreated)
        match b.LastAppliedDate with
        | Some d -> printfn "  Last Applied:  %s" (formatDate d)
        | None -> ()
        printfn ""

    // ---- Match suggestion formatting ----

    let printMatchSuggestions (suggestions: MatchSuggestionDto list) =
        if List.isEmpty suggestions then
            printfn "No match suggestions found."
        else
            let rows =
                suggestions
                |> List.map (fun s ->
                    [ string s.Transaction.Id
                      s.Transaction.Name
                      formatCurrency s.Transaction.Amount
                      string s.RecurringBill.Id
                      s.RecurringBill.Name
                      string s.MatchScore ])

            printTable
                [ "Txn ID"; "Txn Name"; "Txn Amount"; "Bill ID"; "Bill Name"; "Score" ]
                rows

    // ---- Import result formatting ----

    let printImportResult (result: ImportResultDto) =
        printfn "Import complete:"
        printfn "  Imported: %d" result.ImportedCount
        printfn "  Skipped:  %d" result.SkippedCount
        printfn "  Total:    %d" result.TotalCount

    // ---- Link-aware formatting (HATEOAS) ----

    /// Format a single HAL link for display: "METHOD href" or just "href" if GET.
    let formatLink (link: HalLink) : string =
        match link.Method with
        | Some m -> sprintf "%s %s" m link.Href
        | None -> link.Href

    /// Print all available links from a HAL resource.
    let printLinks (links: Map<string, HalLink> option) =
        match links with
        | None -> ()
        | Some m when Map.isEmpty m -> ()
        | Some m ->
            printfn "  Links:"
            m
            |> Map.toList
            |> List.iter (fun (rel, link) ->
                match link.Method with
                | Some method -> printfn "    %-16s %s %s" rel method link.Href
                | None -> printfn "    %-16s %s" rel link.Href)

    /// Print a transaction with its HATEOAS links.
    let printTransactionWithLinks (resource: HalResource<TransactionDto>) =
        let t = resource.Data
        printfn ""
        printfn "Transaction #%d" t.Id
        printfn "=============="
        printfn "  Name:        %s" t.Name
        printfn "  Amount:      %s" (formatCurrency t.Amount)
        printfn "  Date:        %s" (formatDate t.DateCreated)
        printfn "  Type:        %s" (transactionTypeLabel t.Type)
        printfn "  Status:      %s" t.Status
        match t.ClearDate with
        | Some d -> printfn "  Clear Date:  %s" (formatDate d)
        | None -> ()
        match t.ImportId with
        | Some id when not (String.IsNullOrWhiteSpace id) -> printfn "  Import ID:   %s" id
        | _ -> ()
        match t.RecurringBillId with
        | Some billId -> printfn "  Bill ID:     %d" billId
        | None -> ()
        if t.AutoGenerated then printfn "  Auto Generated: yes"
        printLinks resource.Links
        printfn ""

    /// Print a list of transactions with their HATEOAS links in a table.
    /// The "Link" column shows the self link href for each transaction.
    let printTransactionsWithLinks (resources: HalResource<TransactionDto> list) =
        if List.isEmpty resources then
            printfn "No transactions found."
        else
            let rows =
                resources
                |> List.map (fun r ->
                    let t = r.Data
                    let selfHref =
                        r.Links
                        |> Option.bind (fun m -> Map.tryFind "self" m)
                        |> Option.map (fun l -> l.Href)
                        |> Option.defaultValue (sprintf "/api/v1/transactions/%d" t.Id)
                    [ string t.Id
                      t.Name
                      formatCurrency t.Amount
                      formatDate t.DateCreated
                      transactionTypeLabel t.Type
                      t.Status
                      selfHref ])

            printTable
                [ "ID"; "Name"; "Amount"; "Date"; "Type"; "Status"; "Link" ]
                rows

    /// Print a bill with its HATEOAS links.
    let printBillWithLinks (resource: HalResource<RecurringBillDto>) =
        let b = resource.Data
        printfn ""
        printfn "Bill #%d" b.Id
        printfn "========"
        printfn "  Name:          %s" b.Name
        printfn "  Amount:        %s" (formatCurrency b.Amount)
        printfn "  Week of Month: %s" (weekLabel b.WeekOfMonth)
        printfn "  Day of Week:    %s" (dayOfWeekLabel b.DayOfWeek)
        printfn "  Active:        %s" (if b.Active then "yes" else "no")
        printfn "  Created:       %s" (formatDate b.DateCreated)
        match b.LastAppliedDate with
        | Some d -> printfn "  Last Applied:  %s" (formatDate d)
        | None -> ()
        printLinks resource.Links
        printfn ""

    /// Print a list of bills with their HATEOAS links in a table.
    let printBillsWithLinks (resources: HalResource<RecurringBillDto> list) =
        if List.isEmpty resources then
            printfn "No bills found."
        else
            let rows =
                resources
                |> List.map (fun r ->
                    let b = r.Data
                    let selfHref =
                        r.Links
                        |> Option.bind (fun m -> Map.tryFind "self" m)
                        |> Option.map (fun l -> l.Href)
                        |> Option.defaultValue (sprintf "/api/v1/bills/%d" b.Id)
                    [ string b.Id
                      b.Name
                      formatCurrency b.Amount
                      weekLabel b.WeekOfMonth
                      dayOfWeekLabel b.DayOfWeek
                      if b.Active then "yes" else "no"
                      selfHref ])

            printTable
                [ "ID"; "Name"; "Amount"; "Week"; "Day"; "Active"; "Link" ]
                rows

    /// Print balance with its HATEOAS links.
    let printBalanceWithLinks (resource: HalResource<TransactionSum>) =
        let sum = resource.Data
        printfn ""
        printfn "Balance Summary"
        printfn "================"
        printfn "  Total Balance:     %s" (formatCurrency sum.Sum)
        printfn "  Cleared Balance:   %s" (formatCurrency sum.ClearedSum)
        printfn "  Pending Balance:   %s" (formatCurrency sum.PendingSum)
        printfn ""
        printfn "  Cleared Debits:     %s" (formatCurrency sum.ClearedDebitSum)
        printfn "  Cleared Credits:   %s" (formatCurrency sum.ClearedCreditSum)
        printfn "  Pending Debits:    %s" (formatCurrency sum.PendingDebitSum)
        printfn "  Pending Credits:   %s" (formatCurrency sum.PendingCreditSum)
        printLinks resource.Links
        printfn ""

    /// Print match suggestions with their HATEOAS links.
    let printMatchSuggestionsWithLinks (resources: HalResource<MatchSuggestionDto> list) =
        if List.isEmpty resources then
            printfn "No match suggestions found."
        else
            let rows =
                resources
                |> List.map (fun r ->
                    let s = r.Data
                    let matchHref =
                        r.Links
                        |> Option.bind (fun m -> Map.tryFind "execute-match" m)
                        |> Option.map (fun l -> l.Href)
                        |> Option.defaultValue "/api/v1/bills/match"
                    [ string s.Transaction.Id
                      s.Transaction.Name
                      formatCurrency s.Transaction.Amount
                      string s.RecurringBill.Id
                      s.RecurringBill.Name
                      string s.MatchScore
                      matchHref ])

            printTable
                [ "Txn ID"; "Txn Name"; "Txn Amount"; "Bill ID"; "Bill Name"; "Score"; "Match Link" ]
                rows

    /// Print an import result with its HATEOAS links.
    let printImportResultWithLinks (resource: HalResource<ImportResultDto>) =
        let result = resource.Data
        printfn "Import complete:"
        printfn "  Imported: %d" result.ImportedCount
        printfn "  Skipped:  %d" result.SkippedCount
        printfn "  Total:    %d" result.TotalCount
        printLinks resource.Links

// ---- Exit codes ----

module ExitCodes =
    let success = 0
    let generalError = 1
    let authError = 2
    let networkError = 3
