namespace FoxyBalance.Migrations

open FluentMigrator

[<Migration(4L, "Add bill relationship columns to transactions table")>]
type Migration_004_AddBillRelationshipToTransactions() =
    inherit Migration()

    override this.Up() =
        this.Execute.Sql("""
            ALTER TABLE foxybalance_transactions
            ADD COLUMN recurringtransactionid BIGINT REFERENCES foxybalance_recurringtransactions(id) ON DELETE SET NULL,
            ADD COLUMN autogenerated BOOLEAN NOT NULL DEFAULT false;

            CREATE INDEX idx_transactions_recurringtransactionid
            ON foxybalance_transactions (recurringtransactionid)
            WHERE recurringtransactionid IS NOT NULL;
        """)

    override this.Down() =
        this.Execute.Sql("""
            ALTER TABLE foxybalance_transactions
            DROP COLUMN recurringtransactionid,
            DROP COLUMN autogenerated;
        """)
