namespace FoxyBalance.Server.Api.Responses

open System
open FoxyBalance.Database.Models

/// Token response for auth endpoints
type TokenResponse =
    { AccessToken: string
      RefreshToken: string
      ExpiresIn: int
      TokenType: string }

/// API error response
type ApiError =
    { Error: string
      Details: string list option }

/// API Key display info (for web UI)
type ApiKeyDisplayInfo =
    { Id: int64
      KeyPrefix: string
      Name: string
      DateCreated: DateTimeOffset
      LastUsed: DateTimeOffset option
      Active: bool }

/// Helper module to convert domain models to serialization-friendly DTOs
module ApiDtos =
    /// Convert a Transaction to a DTO
    let fromTransaction (t: Transaction) =
        {| Id = t.Id
           Name = t.Name
           Amount = t.Amount
           DateCreated = t.DateCreated
           Type =
            match t.Type with
            | TransactionType.Check _ -> "check"
            | TransactionType.Bill _ -> "bill"
            | TransactionType.Credit -> "credit"
            | TransactionType.Debit -> "debit"
           Status =
            match t.Status with
            | Pending -> "pending"
            | Cleared d -> "cleared"
           ClearDate =
            match t.Status with
            | Pending -> None
            | Cleared d -> Some d
           RecurringBillId = t.RecurringBillId
           AutoGenerated = t.AutoGenerated
           ImportId = t.ImportId |}

    /// Convert a RecurringBill to a DTO
    let fromRecurringBill (b: RecurringBill) =
        {| Id = b.Id
           Name = b.Name
           Amount = b.Amount
           WeekOfMonth = b.WeekOfMonth.ToInt()
           DayOfWeek = int b.DayOfWeek
           DateCreated = b.DateCreated
           LastAppliedDate = b.LastAppliedDate
           Active = b.Active |}
