namespace FoxyBalance.Server.Services

open System
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models

type BillMatchingService(
    recurringBillDb: IRecurringBillDatabase,
    transactionDb: ITransactionDatabase) =

    /// Calculate the target date for a given week and day
    let calculateTargetDateForWeek (weekOfMonth: WeekOfMonth) (dayOfWeek: DayOfWeek) (referenceDate: DateTimeOffset) =
        let firstDayOfMonth = DateTimeOffset(referenceDate.Year, referenceDate.Month, 1, 0, 0, 0, referenceDate.Offset)

        // Find the first occurrence of the target day of week in the month
        let daysUntilTargetDay = (int dayOfWeek - int firstDayOfMonth.DayOfWeek + 7) % 7
        let firstTargetDayOfMonth = firstDayOfMonth.AddDays(float daysUntilTargetDay)

        // Add weeks to get to the target week
        let weeksToAdd = weekOfMonth.ToInt() - 1
        firstTargetDayOfMonth.AddDays(float (weeksToAdd * 7))

    /// Calculate a match score between a transaction and a recurring bill
    let calculateMatchScore (transaction: Transaction) (bill: RecurringBill) =
        // Amount score
        let amountDiff = abs (transaction.Amount - bill.Amount)
        let amountScore =
            if amountDiff = 0M then 100.0M
            elif amountDiff < 0.01M then 90.0M
            elif amountDiff < 1.0M then 70.0M
            elif amountDiff < 5.0M then 50.0M
            else 0.0M

        // Calculate expected date for this bill in the transaction's month
        let expectedDate = calculateTargetDateForWeek bill.WeekOfMonth bill.DayOfWeek transaction.DateCreated

        // Date score based on proximity to expected date
        let daysDiff = abs ((transaction.DateCreated.Date - expectedDate.Date).Days)
        let dateScore =
            if daysDiff <= 1 then 100.0M
            elif daysDiff <= 3 then 80.0M
            elif daysDiff <= 7 then 60.0M
            elif daysDiff <= 14 then 40.0M
            else 0.0M

        // Name similarity (simple contains check)
        let nameScore =
            if transaction.Name.Contains(bill.Name, StringComparison.OrdinalIgnoreCase) ||
               bill.Name.Contains(transaction.Name, StringComparison.OrdinalIgnoreCase) then
                50.0M
            else 0.0M

        // Weighted average: amount is most important, then date, then name
        let totalScore = (amountScore * 0.5M) + (dateScore * 0.4M) + (nameScore * 0.1M)

        { Transaction = transaction
          RecurringBill = bill
          MatchScore = totalScore }

    member this.GetMatchSuggestionsForUser(userId: UserId) =
        task {
            // Get all active recurring bills for the user
            let! bills = recurringBillDb.ListAsync(userId, true)

            // Get all unmatched pending transactions (no RecurringBillId and not auto-generated)
            let! allTransactions = transactionDb.ListAsync(userId, {
                Limit = 1000
                Offset = 0
                Order = Descending
                Status = PendingTransactions
            })

            let unmatchedTransactions =
                allTransactions
                |> Seq.filter (fun t -> t.RecurringBillId.IsNone && not t.AutoGenerated)
                |> List.ofSeq

            // Calculate match scores for all combinations
            let candidates =
                [ for transaction in unmatchedTransactions do
                    for bill in bills do
                        yield calculateMatchScore transaction bill ]
                |> List.filter (fun c -> c.MatchScore >= 40.0M)  // Only show decent matches
                |> List.sortByDescending (fun c -> c.MatchScore)

            return candidates
        }

    member this.MatchTransactionToBill(userId: UserId, transactionId: TransactionId, billId: RecurringBillId) =
        task {
            // Get the transaction
            let! transactionOpt = transactionDb.GetAsync(userId, transactionId)

            match transactionOpt with
            | None -> return Error "Transaction not found"
            | Some transaction ->
                // Find any auto-generated pending transaction for this bill in the same month
                let! allTransactions = transactionDb.ListAsync(userId, {
                    Limit = 1000
                    Offset = 0
                    Order = Descending
                    Status = PendingTransactions
                })

                let autoGeneratedForBill =
                    allTransactions
                    |> Seq.tryFind (fun t ->
                        t.RecurringBillId = Some billId &&
                        t.AutoGenerated &&
                        t.DateCreated.Year = transaction.DateCreated.Year &&
                        t.DateCreated.Month = transaction.DateCreated.Month)

                // If there's an auto-generated transaction, mark it as cleared
                match autoGeneratedForBill with
                | Some autoGen ->
                    let updatedAutoGen : PartialTransaction =
                        { Name = autoGen.Name
                          DateCreated = autoGen.DateCreated
                          Amount = autoGen.Amount
                          Status = Cleared transaction.DateCreated
                          Type = autoGen.Type
                          ImportId = autoGen.ImportId
                          RecurringBillId = autoGen.RecurringBillId
                          AutoGenerated = autoGen.AutoGenerated }

                    let! _ = transactionDb.UpdateAsync(userId, autoGen.Id, updatedAutoGen)
                    ()
                | None -> ()

                // Update the imported transaction to link it to the bill
                let updatedTransaction : PartialTransaction =
                    { Name = transaction.Name
                      DateCreated = transaction.DateCreated
                      Amount = transaction.Amount
                      Status = transaction.Status
                      Type = transaction.Type
                      ImportId = transaction.ImportId
                      RecurringBillId = Some billId
                      AutoGenerated = transaction.AutoGenerated }

                let! updated = transactionDb.UpdateAsync(userId, transactionId, updatedTransaction)

                return Ok updated
        }
