namespace FoxyBalance.Server.Services

open System
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models
open Microsoft.Extensions.Logging

type RecurringBillApplicationService(
    logger: ILogger<RecurringBillApplicationService>,
    recurringBillDb: IRecurringBillDatabase,
    transactionDb: ITransactionDatabase) =

    /// Calculate the target date for a given week and day
    let calculateTargetDateForWeek (weekOfMonth: WeekOfMonth) (dayOfWeek: DayOfWeek) (referenceDate: DateTimeOffset) =
        let firstDayOfMonth = DateTimeOffset(referenceDate.Year, referenceDate.Month, 1, 0, 0, 0, referenceDate.Offset)

        // Find the first occurrence of the target day of week in the month
        let daysUntilTargetDay = (int dayOfWeek - int firstDayOfMonth.DayOfWeek + 7) % 7
        let firstTargetDayOfMonth = firstDayOfMonth.AddDays(float daysUntilTargetDay)

        // Add weeks to get to the target week
        let weeksToAdd = weekOfMonth.ToInt() - 1
        firstTargetDayOfMonth.AddDays(float (weeksToAdd * 7))

    /// Calculate the target date for date-based bills, handling edge cases
    let calculateTargetDateForDayOfMonth (dayOfMonth: int) (referenceDate: DateTimeOffset) =
        let year = referenceDate.Year
        let month = referenceDate.Month
        let daysInMonth = DateTime.DaysInMonth(year, month)

        // If the specified day doesn't exist in this month, use the last day
        let actualDay = min dayOfMonth daysInMonth

        DateTimeOffset(year, month, actualDay, 0, 0, 0, referenceDate.Offset)

    /// Calculate target date based on schedule type
    let calculateTargetDate (bill: RecurringBill) (referenceDate: DateTimeOffset) =
        match bill.Schedule with
        | WeekBased(week, day) ->
            calculateTargetDateForWeek week day referenceDate
        | DateBased(dayOfMonth) ->
            calculateTargetDateForDayOfMonth dayOfMonth referenceDate

    /// Check if we're in the correct week to apply a bill
    let shouldApplyBillNow (bill: RecurringBill) (currentDate: DateTimeOffset) =
        let targetDate = calculateTargetDate bill currentDate

        // Apply if we're on or after the target date but haven't applied this month
        let isAfterTargetDate = currentDate.Date >= targetDate.Date
        let notAppliedThisMonth =
            match bill.LastAppliedDate with
            | None -> true
            | Some lastApplied ->
                lastApplied.Year < currentDate.Year || lastApplied.Month < currentDate.Month

        isAfterTargetDate && notAppliedThisMonth

    member this.ApplyBillsForAllUsers() =
        task {
            let currentDate = DateTimeOffset.UtcNow
            logger.LogInformation("Starting recurring bill application process at {CurrentDate}", currentDate)

            let! billsDue = recurringBillDb.GetBillsDueForApplicationAsync(currentDate)
            let billsDueList = List.ofSeq billsDue

            logger.LogInformation("Found {BillCount} bills to evaluate", List.length billsDueList)

            let mutable appliedCount = 0

            for (userId, bill) in billsDueList do
                if shouldApplyBillNow bill currentDate then
                    try
                        // Create a pending transaction from this bill
                        let targetDate = calculateTargetDate bill currentDate
                        let partialTransaction : PartialTransaction =
                            { Name = bill.Name
                              DateCreated = targetDate
                              Amount = bill.Amount
                              Status = Pending
                              Type = Bill { Recurring = true }
                              ImportId = None
                              RecurringBillId = Some bill.Id
                              AutoGenerated = true }

                        // Create the transaction
                        let! _createdTransaction = transactionDb.CreateAsync(userId, partialTransaction)

                        // Update the bill's last applied date
                        do! recurringBillDb.UpdateLastAppliedDateAsync(userId, bill.Id, currentDate)

                        logger.LogInformation("Applied recurring bill {BillId} ({BillName}) for user {UserId} with amount {Amount}",
                            bill.Id, bill.Name, userId, bill.Amount)

                        appliedCount <- appliedCount + 1
                    with ex ->
                        logger.LogError(ex, "Failed to apply recurring bill {BillId} for user {UserId}", bill.Id, userId)

            logger.LogInformation("Completed recurring bill application. Applied {AppliedCount} bills", appliedCount)
        }
