namespace FoxyBalance.Server.Services

open System
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models
open Microsoft.Extensions.Logging

type RecurringTransactionApplicationService(
    logger: ILogger<RecurringTransactionApplicationService>,
    recurringTransactionDb: IRecurringTransactionDatabase,
    transactionDb: ITransactionDatabase) =

    /// Check if we're in the correct week to apply a transaction
    let shouldApplyNow (rt: RecurringTransaction) (currentDate: DateTimeOffset) =
        // Apply if we're on or after the target date but haven't applied this month.
        // If the target date doesn't exist in this month (e.g. the 31st in a 30-day month),
        // the recurring transaction is skipped for this month.
        match RecurringSchedule.targetDateForMonth rt.Schedule currentDate with
        | None -> false
        | Some targetDate ->
            let isAfterTargetDate = currentDate.Date >= targetDate.Date
            let notAppliedThisMonth =
                match rt.LastAppliedDate with
                | None -> true
                | Some lastApplied ->
                    lastApplied.Year < currentDate.Year || lastApplied.Month < currentDate.Month

            isAfterTargetDate && notAppliedThisMonth

    member this.ApplyRecurringTransactionsForAllUsers() =
        task {
            let currentDate = DateTimeOffset.UtcNow
            logger.LogInformation("Starting recurring transaction application process at {CurrentDate}", currentDate)

            let! transactionsDue = recurringTransactionDb.GetRecurringTransactionsDueForApplicationAsync(currentDate)
            let transactionsDueList = List.ofSeq transactionsDue

            logger.LogInformation("Found {TransactionCount} recurring transactions to evaluate", List.length transactionsDueList)

            let mutable appliedCount = 0

            for (userId, rt) in transactionsDueList do
                if shouldApplyNow rt currentDate then
                    try
                        // Create a pending transaction from this recurring transaction
                        let targetDate =
                            // shouldApplyNow already validated that the target date exists for this month
                            match RecurringSchedule.targetDateForMonth rt.Schedule currentDate with
                            | Some d -> d
                            | None -> currentDate

                        let partialTransaction : PartialTransaction =
                            { Name = rt.Name
                              DateCreated = targetDate
                              Amount = rt.Amount
                              Status = Pending
                              Type = Bill { Recurring = true }
                              ImportId = None
                              RecurringTransactionId = Some rt.Id
                              AutoGenerated = true
                              MatchedTransactionId = None }

                        // Create the transaction
                        let! _createdTransaction = transactionDb.CreateAsync(userId, partialTransaction)

                        // Update the recurring transaction's last applied date
                        do! recurringTransactionDb.UpdateLastAppliedDateAsync(userId, rt.Id, currentDate)

                        logger.LogInformation("Applied recurring transaction {TransactionId} ({TransactionName}) for user {UserId} with amount {Amount}",
                            rt.Id, rt.Name, userId, rt.Amount)

                        appliedCount <- appliedCount + 1
                    with ex ->
                        logger.LogError(ex, "Failed to apply recurring transaction {TransactionId} for user {UserId}", rt.Id, userId)

            logger.LogInformation("Completed recurring transaction application. Applied {AppliedCount} transactions", appliedCount)
        }
