namespace FoxyBalance.Server.Api

open System
open FoxyBalance.Database.Models

/// HAL link representation
type HalLink =
    { Href: string
      Method: string option
      Templated: bool option }

/// Type-safe link relations for HATEOAS
type LinkRel =
    | Self
    | Collection
    | Item
    | Next
    | Prev
    | First
    | Last
    | Create
    | Update
    | Delete
    | Balance
    | Transactions
    | Transaction of TransactionId
    | Bills
    | Bill of RecurringBillId
    | MatchSuggestions
    | ExecuteMatch
    | ToggleActive
    | Import
    | TokenRefresh
    | ApiKeys

    member this.AsString() =
        match this with
        | Self -> "self"
        | Collection -> "collection"
        | Item -> "item"
        | Next -> "next"
        | Prev -> "prev"
        | First -> "first"
        | Last -> "last"
        | Create -> "create"
        | Update -> "update"
        | Delete -> "delete"
        | Balance -> "balance"
        | Transactions -> "transactions"
        | Transaction _ -> "transaction"
        | Bills -> "bills"
        | Bill _ -> "bill"
        | MatchSuggestions -> "match-suggestions"
        | ExecuteMatch -> "execute-match"
        | ToggleActive -> "toggle-active"
        | Import -> "import"
        | TokenRefresh -> "token-refresh"
        | ApiKeys -> "api-keys"

/// HAL links as a map from relation to link
type HalLinks = Map<string, HalLink>

/// HAL embedded resources
type HalEmbedded = Map<string, obj>

/// HAL resource wrapper with strong typing
type HalResource<'T> =
    { Data: 'T
      Links: HalLinks
      Embedded: HalEmbedded option }

/// Paginated HAL collection
type HalCollection<'T> =
    { Items: 'T list
      Page: int
      TotalPages: int
      TotalCount: int
      Links: HalLinks }

/// API Session representing an authenticated API request
type ApiSession =
    { UserId: UserId
      ApiKeyId: int64 option }

/// Token exchange request
[<CLIMutable>]
type TokenExchangeRequest = { ApiKey: string; ApiSecret: string }

/// Token refresh request
[<CLIMutable>]
type TokenRefreshRequest = { RefreshToken: string }

/// Token response for auth endpoints
type TokenResponse =
    { AccessToken: string
      RefreshToken: string
      ExpiresIn: int
      TokenType: string }

/// Transaction request for API
[<CLIMutable>]
type ApiTransactionRequest =
    { Name: string
      Amount: string
      Date: string
      ClearDate: string
      TransactionType: string
      CheckNumber: string }

/// Recurring bill request for API
[<CLIMutable>]
type ApiRecurringBillRequest =
    { Name: string
      Amount: string
      ScheduleType: string
      WeekOfMonth: string
      DayOfWeek: string
      DayOfMonth: string }

/// Match execution request
[<CLIMutable>]
type ApiMatchRequest = { TransactionId: int64; BillId: int64 }

/// Bulk import request
[<CLIMutable>]
type ApiBulkImportRequest =
    { Format: string; Transactions: string }

/// API error response
type ApiError =
    { Error: string
      Details: string list option }

/// API Key display info (for web UI)
type ApiKeyDisplayInfo =
    { Id: int64
      KeyPrefix: string
      Name: string
      DateCreated: DateTimeOffset
      LastUsed: DateTimeOffset option
      Active: bool }

/// Helper module to convert domain models to serialization-friendly DTOs
module ApiDtos =
    /// Convert a Transaction to a DTO
    let fromTransaction (t: Transaction) =
        {| Id = t.Id
           Name = t.Name
           Amount = t.Amount
           DateCreated = t.DateCreated
           Type =
            match t.Type with
            | TransactionType.Check _ -> "check"
            | TransactionType.Bill _ -> "bill"
            | TransactionType.Credit -> "credit"
            | TransactionType.Debit -> "debit"
           Status =
            match t.Status with
            | Pending -> "pending"
            | Cleared d -> "cleared"
           ClearDate =
            match t.Status with
            | Pending -> None
            | Cleared d -> Some d
           RecurringBillId = t.RecurringBillId
           AutoGenerated = t.AutoGenerated
           ImportId = t.ImportId |}

    /// Convert a RecurringBill to a DTO
    let fromRecurringBill (b: RecurringBill) =
        let (scheduleType, weekOfMonth, dayOfWeek, dayOfMonth) =
            match b.Schedule with
            | WeekBased(week, day) -> ("week", Some (week.ToInt()), Some (int day), None)
            | DateBased(dom) -> ("date", None, None, Some dom)

        {| Id = b.Id
           Name = b.Name
           Amount = b.Amount
           ScheduleType = scheduleType
           WeekOfMonth = weekOfMonth
           DayOfWeek = dayOfWeek
           DayOfMonth = dayOfMonth
           DateCreated = b.DateCreated
           LastAppliedDate = b.LastAppliedDate
           Active = b.Active |}
