namespace FoxyBalance.CLI.Tests

open System
open System.Threading.Tasks
open FoxyBalance.CLI.Domain
open Xunit
open VerifyXunit

/// Snapshot tests using Verify to verify that encoded JSON output matches expected snapshots.
type EncoderSnapshotTests() =
    inherit VerifyBase()

    // ---- Request encoders ----

    [<Fact>]
    member self.``TokenExchangeRequest encodes to expected JSON`` () = task {
        let request : TokenExchangeRequest =
            { ApiKey = "test-api-key"
              ApiSecret = "test-api-secret" }
        let json = Codecs.serialize Codecs.tokenExchangeRequestEncoder request
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``TokenRefreshRequest encodes to expected JSON`` () = task {
        let request : TokenRefreshRequest = { RefreshToken = "refresh-token-abc-123" }
        let json = Codecs.serialize Codecs.tokenRefreshRequestEncoder request
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``ApiTransactionRequest encodes to expected JSON`` () = task {
        let request : ApiTransactionRequest =
            { Name = "Coffee"
              Amount = "5.50"
              Date = "2024-01-15"
              ClearDate = ""
              TransactionType = "debit"
              CheckNumber = "" }
        let json = Codecs.serialize Codecs.apiTransactionRequestEncoder request
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``ApiRecurringBillRequest encodes to expected JSON`` () = task {
        let request : ApiRecurringBillRequest =
            { Name = "Rent"
              Amount = "1500.00"
              WeekOfMonth = "1"
              DayOfWeek = "1" }
        let json = Codecs.serialize Codecs.apiRecurringBillRequestEncoder request
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``ApiMatchRequest encodes to expected JSON`` () = task {
        let request : ApiMatchRequest = { TransactionId = 42L; BillId = 7L }
        let json = Codecs.serialize Codecs.apiMatchRequestEncoder request
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``ApiBulkImportRequest encodes to expected JSON`` () = task {
        let request : ApiBulkImportRequest =
            { Format = "capital-one"
              Transactions = "transaction_date,description,amount,debit\r\n2024-01-15,Coffee,5.50,\r\n" }
        let json = Codecs.serialize Codecs.apiBulkImportRequestEncoder request
        let! _ = self.VerifyJson(json)
        return ()
    }

    // ---- DTO encoders ----

    [<Fact>]
    member self.``TokenResponse encodes to expected JSON`` () = task {
        let dto : TokenResponse =
            { AccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
              RefreshToken = "refresh-token-xyz"
              ExpiresIn = 3600
              TokenType = "Bearer" }
        let json = Codecs.serialize Codecs.tokenResponseEncoder dto
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``TransactionDto encodes to expected JSON with all fields`` () = task {
        let dto : TransactionDto =
            { Id = 42L
              Name = "Test Transaction"
              Amount = 99.50m
              DateCreated = DateTimeOffset(2024, 1, 15, 10, 30, 0, TimeSpan.Zero)
              Type = "debit"
              Status = "pending"
              ClearDate = Some (DateTimeOffset(2024, 1, 16, 0, 0, 0, TimeSpan.Zero))
              RecurringBillId = Some 5L
              AutoGenerated = true
              ImportId = Some "import-123" }
        let json = Codecs.serialize Codecs.transactionDtoEncoder dto
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``TransactionDto encodes to expected JSON with minimal fields`` () = task {
        let dto : TransactionDto =
            { Id = 1L
              Name = "Coffee"
              Amount = 5.50m
              DateCreated = DateTimeOffset(2024, 1, 15, 10, 30, 0, TimeSpan.Zero)
              Type = "debit"
              Status = "cleared"
              ClearDate = None
              RecurringBillId = None
              AutoGenerated = false
              ImportId = None }
        let json = Codecs.serialize Codecs.transactionDtoEncoder dto
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``RecurringBillDto encodes to expected JSON`` () = task {
        let dto : RecurringBillDto =
            { Id = 10L
              Name = "Rent"
              Amount = 1500.00m
              WeekOfMonth = 1
              DayOfWeek = 1
              DateCreated = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)
              LastAppliedDate = Some (DateTimeOffset(2024, 9, 1, 0, 0, 0, TimeSpan.Zero))
              Active = true }
        let json = Codecs.serialize Codecs.recurringBillDtoEncoder dto
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``TransactionSum encodes to expected JSON`` () = task {
        let dto : TransactionSum =
            { Sum = 1000.00m
              PendingSum = 200.00m
              ClearedSum = 800.00m
              PendingDebitSum = 150.00m
              ClearedDebitSum = 600.00m
              PendingCreditSum = 50.00m
              ClearedCreditSum = 200.00m }
        let json = Codecs.serialize Codecs.transactionSumEncoder dto
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``ImportResultDto encodes to expected JSON`` () = task {
        let dto : ImportResultDto =
            { ImportedCount = 42
              TotalCount = 50
              SkippedCount = 8 }
        let json = Codecs.serialize Codecs.importResultDtoEncoder dto
        let! _ = self.VerifyJson(json)
        return ()
    }

    // ---- HAL resource encoders ----

    [<Fact>]
    member self.``HalResource<TransactionDto> encodes to expected JSON with links`` () = task {
        let resource : HalResource<TransactionDto> = {
            Data = {
                Id = 1L
                Name = "Test"
                Amount = 50.00m
                DateCreated = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)
                Type = "debit"
                Status = "pending"
                ClearDate = None
                RecurringBillId = None
                AutoGenerated = false
                ImportId = None }
            Links = Some (Map.ofList [
                "self", { Href = "/api/v1/transactions/1"; Method = None; Templated = None }
                "update", { Href = "/api/v1/transactions/1"; Method = Some "PUT"; Templated = None }
                "delete", { Href = "/api/v1/transactions/1"; Method = Some "DELETE"; Templated = None }
            ])
            Embedded = None }
        let json = Codecs.serializeHalResource Codecs.transactionDtoEncoder resource
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``HalResource<TransactionDto> encodes without links`` () = task {
        let resource : HalResource<TransactionDto> = {
            Data = {
                Id = 1L
                Name = "No Links"
                Amount = 10.00m
                DateCreated = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)
                Type = "credit"
                Status = "cleared"
                ClearDate = None
                RecurringBillId = None
                AutoGenerated = false
                ImportId = None }
            Links = None
            Embedded = None }
        let json = Codecs.serializeHalResource Codecs.transactionDtoEncoder resource
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``HalCollection<TransactionDto> encodes to expected JSON`` () = task {
        let collection : HalCollection<TransactionDto> = {
            Items = [
                { Data = {
                    Id = 1L
                    Name = "Tx1"
                    Amount = 10.00m
                    DateCreated = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)
                    Type = "debit"
                    Status = "pending"
                    ClearDate = None
                    RecurringBillId = None
                    AutoGenerated = false
                    ImportId = None }
                  Links = Some (Map.ofList [
                    "self", { Href = "/api/v1/transactions/1"; Method = None; Templated = None }
                  ])
                  Embedded = None }
                { Data = {
                    Id = 2L
                    Name = "Tx2"
                    Amount = 20.00m
                    DateCreated = DateTimeOffset(2024, 1, 2, 0, 0, 0, TimeSpan.Zero)
                    Type = "credit"
                    Status = "cleared"
                    ClearDate = None
                    RecurringBillId = None
                    AutoGenerated = false
                    ImportId = None }
                  Links = None
                  Embedded = None }
            ]
            Page = 1
            TotalPages = 3
            TotalCount = 25
            Links = Some (Map.ofList [
                "self", { Href = "/api/v1/transactions?page=1"; Method = None; Templated = None }
                "next", { Href = "/api/v1/transactions?page=2"; Method = None; Templated = None }
                "create", { Href = "/api/v1/transactions"; Method = Some "POST"; Templated = None }
            ]) }
        let json = Codecs.serializeHalCollection Codecs.transactionDtoEncoder collection
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``HalLink encodes to expected JSON with method and templated`` () = task {
        let link : HalLink = {
            Href = "/api/v1/bills/match"
            Method = Some "POST"
            Templated = Some true }
        let json = Codecs.serialize Codecs.halLinkEncoder link
        let! _ = self.VerifyJson(json)
        return ()
    }

    [<Fact>]
    member self.``HalLink encodes to expected JSON without optional fields`` () = task {
        let link : HalLink = {
            Href = "/api/v1/balance"
            Method = None
            Templated = None }
        let json = Codecs.serialize Codecs.halLinkEncoder link
        let! _ = self.VerifyJson(json)
        return ()
    }
