namespace FoxyBalance.Database.Tests

open System
open Faqt
open Faqt.Operators
open FoxyBalance.Database
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models
open FoxyBalance.Database.Tests.Domain
open FoxyBalance.Server.Services
open Xunit

[<Collection("BillMatchingService")>]
type BillMatchingServiceTests(fixture: DbContainerFixture) =
    let billDatabase: IRecurringBillDatabase = RecurringBillDatabase(TestDatabaseOptions fixture)
    let transactionDatabase: ITransactionDatabase = TransactionDatabase(TestDatabaseOptions fixture)
    let userDatabase: IUserDatabase = UserDatabase(TestDatabaseOptions fixture)
    let service = BillMatchingService(billDatabase, transactionDatabase)
    let bogus = Bogus.Faker()

    let createUser () =
        userDatabase.CreateAsync { EmailAddress = bogus.Internet.Email(); HashedPassword = bogus.Internet.Password() }

    let createBill (userId: UserId) (name: string) (amount: decimal) (week: WeekOfMonth) (day: DayOfWeek) =
        task {
            let partialBill: PartialRecurringBill =
                { Name = name
                  Amount = amount
                  WeekOfMonth = week
                  DayOfWeek = day }
            return! billDatabase.CreateAsync(userId, partialBill)
        }

    let createTransaction (userId: UserId) (name: string) (amount: decimal) (date: DateTimeOffset) =
        task {
            let partialTransaction: PartialTransaction =
                { Name = name
                  Amount = amount
                  DateCreated = date
                  Status = Pending
                  Type = Debit
                  ImportId = Some (Guid.NewGuid().ToString())
                  RecurringBillId = None
                  AutoGenerated = false }
            return! transactionDatabase.CreateAsync(userId, partialTransaction)
        }

    [<Fact>]
    member _.``Scoring should give 100 points for exact amount match``() =
        task {
            // Setup
            let! user = createUser ()
            let amount = 125.50M

            let! bill = createBill user.Id "Electric Bill" amount FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero) // First Monday of Jan 2024
            let! transaction = createTransaction user.Id "ELECTRIC COMPANY" amount targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList
            %matchesList.Should().NotBeEmpty()

            let match' = matchesList |> List.find (fun m -> m.Transaction.Id = transaction.Id && m.RecurringBill.Id = bill.Id)

            // Exact amount (100 * 0.5) + exact date (100 * 0.4) + name match (50 * 0.1) = 95
            %match'.MatchScore.Should().BeGreaterThanOrEqualTo(90M)
        }

    [<Fact>]
    member _.``Scoring should decrease with amount difference``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Water Bill" 100M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create transactions with different amounts
            let! exactMatch = createTransaction user.Id "Water" 100M targetDate
            let! smallDiff = createTransaction user.Id "Water" 100.50M targetDate
            let! largeDiff = createTransaction user.Id "Water" 110M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let exactScore = matchesList |> List.find (fun m -> m.Transaction.Id = exactMatch.Id) |> _.MatchScore
            let smallDiffScore = matchesList |> List.find (fun m -> m.Transaction.Id = smallDiff.Id) |> _.MatchScore
            let largeDiffScore = matchesList |> List.find (fun m -> m.Transaction.Id = largeDiff.Id) |> _.MatchScore

            %exactScore.Should().BeGreaterThan(smallDiffScore)
            %smallDiffScore.Should().BeGreaterThan(largeDiffScore)
        }

    [<Fact>]
    member _.``Scoring should decrease with date distance``() =
        task {
            // Setup
            let! user = createUser ()

            // Bill scheduled for first Monday of month
            let! bill = createBill user.Id "Internet Bill" 75M FirstWeek DayOfWeek.Monday

            // First Monday of January 2024 is January 1st
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create transactions on different dates
            let! exactDate = createTransaction user.Id "Internet" 75M targetDate
            let! twoDaysAfter = createTransaction user.Id "Internet" 75M (targetDate.AddDays(2.0))
            let! oneWeekAfter = createTransaction user.Id "Internet" 75M (targetDate.AddDays(7.0))
            let! twoWeeksAfter = createTransaction user.Id "Internet" 75M (targetDate.AddDays(14.0))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let exactScore = matchesList |> List.find (fun m -> m.Transaction.Id = exactDate.Id) |> _.MatchScore
            let twoDaysScore = matchesList |> List.find (fun m -> m.Transaction.Id = twoDaysAfter.Id) |> _.MatchScore
            let oneWeekScore = matchesList |> List.find (fun m -> m.Transaction.Id = oneWeekAfter.Id) |> _.MatchScore
            let twoWeeksScore = matchesList |> List.find (fun m -> m.Transaction.Id = twoWeeksAfter.Id) |> _.MatchScore

            %exactScore.Should().BeGreaterThan(twoDaysScore)
            %twoDaysScore.Should().BeGreaterThan(oneWeekScore)
            %oneWeekScore.Should().BeGreaterThan(twoWeeksScore)
        }

    [<Fact>]
    member _.``Scoring should give bonus points for name match``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Gas Bill" 60M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create transactions with and without name match
            let! withNameMatch = createTransaction user.Id "GAS COMPANY - Gas Bill Payment" 60M targetDate
            let! withoutNameMatch = createTransaction user.Id "UTILITY PAYMENT" 60M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let withNameScore = matchesList |> List.find (fun m -> m.Transaction.Id = withNameMatch.Id) |> _.MatchScore
            let withoutNameScore = matchesList |> List.find (fun m -> m.Transaction.Id = withoutNameMatch.Id) |> _.MatchScore

            // Name match should add 50 * 0.1 = 5 points
            %withNameScore.Should().BeGreaterThan(withoutNameScore)
            %(withNameScore - withoutNameScore).Should().BeCloseTo(5M, 1M)
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should not include auto-generated transactions``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Phone Bill" 50M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create an auto-generated transaction
            let autoGenTransaction: PartialTransaction =
                { Name = "Phone Bill"
                  Amount = 50M
                  DateCreated = targetDate
                  Status = Pending
                  Type = Debit
                  ImportId = None
                  RecurringBillId = Some bill.Id
                  AutoGenerated = true }
            let! autoGen = transactionDatabase.CreateAsync(user.Id, autoGenTransaction)

            // Create a normal imported transaction
            let! imported = createTransaction user.Id "Phone Company" 50M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Should only have the imported transaction, not the auto-generated one
            let transactionIds = matchesList |> List.map (_.Transaction.Id) |> Set.ofList
            %transactionIds.Should().Contain(imported.Id)
            %transactionIds.Should().NotContain(autoGen.Id)
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should not include already-matched transactions``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Cable Bill" 80M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create a transaction already matched to a bill
            let matchedTransaction: PartialTransaction =
                { Name = "Cable Company"
                  Amount = 80M
                  DateCreated = targetDate
                  Status = Pending
                  Type = Debit
                  ImportId = Some (Guid.NewGuid().ToString())
                  RecurringBillId = Some bill.Id
                  AutoGenerated = false }
            let! matched = transactionDatabase.CreateAsync(user.Id, matchedTransaction)

            // Create an unmatched transaction
            let! unmatched = createTransaction user.Id "Cable Co" 80M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Should only have the unmatched transaction
            let transactionIds = matchesList |> List.map (_.Transaction.Id) |> Set.ofList
            %transactionIds.Should().Contain(unmatched.Id)
            %transactionIds.Should().NotContain(matched.Id)
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should filter out low-score matches``() =
        task {
            // Setup
            let! user = createUser ()

            // Create a bill for $100
            let! bill = createBill user.Id "Expensive Bill" 100M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create a transaction with very different amount and far-off date (should score low)
            let! poorMatch = createTransaction user.Id "Something Else" 10M (targetDate.AddDays(30.0))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Poor match should be filtered out (score < 40)
            %matchesList.Should().AllSatisfy(fun m -> m.MatchScore.Should().BeGreaterThanOrEqualTo(40M))
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should sort by score descending``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Utility Bill" 100M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create transactions with different match qualities
            let! perfectMatch = createTransaction user.Id "Utility Bill Payment" 100M targetDate
            let! goodMatch = createTransaction user.Id "Utility" 101M (targetDate.AddDays(1.0))
            let! okMatch = createTransaction user.Id "Payment" 105M (targetDate.AddDays(5.0))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Should be sorted by score descending
            %matchesList.Should().BeStrictlyDescendingBy(_.MatchScore)
        }

    [<Fact>]
    member _.``MatchTransactionToBill should link transaction to bill``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Mortgage" 1500M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)
            let! transaction = createTransaction user.Id "BANK MORTGAGE PAYMENT" 1500M targetDate

            // Act
            let! result = service.MatchTransactionToBill(user.Id, transaction.Id, bill.Id)

            // Assert
            %result.Should().BeOk()

            match result with
            | Ok updatedTransaction ->
                %updatedTransaction.RecurringBillId.Should().Be(Some bill.Id)
            | Error _ -> failwith "Unexpected error"
        }

    [<Fact>]
    member _.``MatchTransactionToBill should mark auto-generated transaction as cleared``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Rent" 1200M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create an auto-generated pending transaction from the bill
            let autoGenTransaction: PartialTransaction =
                { Name = "Rent"
                  Amount = 1200M
                  DateCreated = targetDate
                  Status = Pending
                  Type = Debit
                  ImportId = None
                  RecurringBillId = Some bill.Id
                  AutoGenerated = true }
            let! autoGen = transactionDatabase.CreateAsync(user.Id, autoGenTransaction)

            // Create an imported transaction
            let! imported = createTransaction user.Id "LANDLORD RENT PAYMENT" 1200M (targetDate.AddDays(1.0))

            // Act
            let! result = service.MatchTransactionToBill(user.Id, imported.Id, bill.Id)

            // Assert
            %result.Should().BeOk()

            // Check that auto-generated transaction is now cleared
            let! autoGenUpdated = transactionDatabase.GetAsync(user.Id, autoGen.Id)
            %autoGenUpdated.Should().BeSome()

            match autoGenUpdated.Value.Status with
            | Cleared clearedDate ->
                %clearedDate.Should().BeCloseTo(imported.DateCreated, TimeSpan.FromSeconds 1L)
            | Pending ->
                failwith "Auto-generated transaction should be cleared"
        }

    [<Fact>]
    member _.``MatchTransactionToBill should return error for non-existent transaction``() =
        task {
            // Setup
            let! user = createUser ()
            let! bill = createBill user.Id "Test Bill" 50M FirstWeek DayOfWeek.Monday
            let nonExistentTransactionId = 999999L

            // Act
            let! result = service.MatchTransactionToBill(user.Id, nonExistentTransactionId, bill.Id)

            // Assert
            %result.Should().BeError()
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should only show bills for the specific user``() =
        task {
            // Setup
            let! user1 = createUser ()
            let! user2 = createUser ()

            // Create bills for both users
            let! user1Bill = createBill user1.Id "User1 Bill" 100M FirstWeek DayOfWeek.Monday
            let! user2Bill = createBill user2.Id "User2 Bill" 100M FirstWeek DayOfWeek.Monday

            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create transactions for both users
            let! user1Transaction = createTransaction user1.Id "Payment 1" 100M targetDate
            let! user2Transaction = createTransaction user2.Id "Payment 2" 100M targetDate

            // Act
            let! user1Matches = service.GetMatchSuggestionsForUser(user1.Id)
            let! user2Matches = service.GetMatchSuggestionsForUser(user2.Id)

            // Assert
            let user1MatchesList = user1Matches |> Seq.toList
            let user2MatchesList = user2Matches |> Seq.toList

            // User1 should only see their own bill and transaction
            %user1MatchesList.Should().AllSatisfy(fun m ->
                m.Transaction.Id.Should().Be(user1Transaction.Id)
                m.RecurringBill.Id.Should().Be(user1Bill.Id))

            // User2 should only see their own bill and transaction
            %user2MatchesList.Should().AllSatisfy(fun m ->
                m.Transaction.Id.Should().Be(user2Transaction.Id)
                m.RecurringBill.Id.Should().Be(user2Bill.Id))
        }

    [<Fact>]
    member _.``Scoring should calculate correct date for second week Wednesday``() =
        task {
            // Setup
            let! user = createUser ()

            // Bill scheduled for second Wednesday
            let! bill = createBill user.Id "Trash Service" 25M SecondWeek DayOfWeek.Wednesday

            // Second Wednesday of January 2024 is January 10th
            let targetDate = DateTimeOffset(2024, 1, 10, 0, 0, 0, TimeSpan.Zero)

            // Create transaction on the exact target date
            let! exactMatch = createTransaction user.Id "Waste Management" 25M targetDate

            // Create transaction on wrong week (first Wednesday = Jan 3)
            let! wrongWeek = createTransaction user.Id "Waste Management" 25M (DateTimeOffset(2024, 1, 3, 0, 0, 0, TimeSpan.Zero))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let exactScore = matchesList |> List.find (fun m -> m.Transaction.Id = exactMatch.Id) |> _.MatchScore
            let wrongWeekScore = matchesList |> List.find (fun m -> m.Transaction.Id = wrongWeek.Id) |> _.MatchScore

            // Exact date should score higher (7 days difference)
            %exactScore.Should().BeGreaterThan(wrongWeekScore)
        }
