namespace FoxyBalance.Database.Tests

open System
open Faqt
open Faqt.Operators
open FoxyBalance.Database
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models
open FoxyBalance.Database.Tests.Domain
open FoxyBalance.Server.Services
open Xunit

[<Collection("BillMatchingService")>]
type BillMatchingServiceTests(fixture: DbContainerFixture) =
    let billDatabase: IRecurringBillDatabase = RecurringBillDatabase(TestDatabaseOptions fixture)
    let transactionDatabase: ITransactionDatabase = TransactionDatabase(TestDatabaseOptions fixture)
    let userDatabase: IUserDatabase = UserDatabase(TestDatabaseOptions fixture)
    let service = BillMatchingService(billDatabase, transactionDatabase)
    let bogus = Bogus.Faker()

    let createUser () =
        userDatabase.CreateAsync { EmailAddress = bogus.Internet.Email(); HashedPassword = bogus.Internet.Password() }

    let createBill (userId: UserId) (name: string) (amount: decimal) (week: WeekOfMonth) (day: DayOfWeek) =
        task {
            let partialBill: PartialRecurringBill =
                { Name = name
                  Amount = amount
                  Schedule = WeekBased(week, day) }
            return! billDatabase.CreateAsync(userId, partialBill)
        }

    // Mirrors BillMatchingService.calculateTargetDateForWeek so tests can produce dates that
    // align with the bill schedule and stay within the 60-day match-candidate window.
    let calculateExpectedDate (week: WeekOfMonth) (day: DayOfWeek) =
        let now = DateTimeOffset.UtcNow
        let firstDayOfMonth = DateTimeOffset(now.Year, now.Month, 1, 0, 0, 0, TimeSpan.Zero)
        let daysUntilTargetDay = (int day - int firstDayOfMonth.DayOfWeek + 7) % 7
        let firstTargetDayOfMonth = firstDayOfMonth.AddDays(float daysUntilTargetDay)
        let weeksToAdd = week.ToInt() - 1
        firstTargetDayOfMonth.AddDays(float (weeksToAdd * 7))

    let createTransaction (userId: UserId) (name: string) (amount: decimal) (date: DateTimeOffset) =
        task {
            let partialTransaction: PartialTransaction =
                { Name = name
                  Amount = amount
                  DateCreated = date
                  Status = Pending
                  Type = Debit
                  ImportId = Some (Guid.NewGuid().ToString())
                  RecurringBillId = None
                  AutoGenerated = false }
            return! transactionDatabase.CreateAsync(userId, partialTransaction)
        }

    [<Fact>]
    member _.``Scoring should give 100 points for exact amount match``() =
        task {
            // Setup
            let! user = createUser ()
            let amount = 125.50M

            let! bill = createBill user.Id "Electric Bill" amount FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday
            let! transaction = createTransaction user.Id "ELECTRIC COMPANY" amount targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList
            %matchesList.Should().NotBeEmpty()

            let match' = matchesList |> List.find (fun m -> m.Transaction.Id = transaction.Id && m.RecurringBill.Id = bill.Id)

            // Exact amount (100 * 0.45) + exact date (100 * 0.35) + no name match (0 * 0.05) + no history (0 * 0.15) = 80
            %match'.MatchScore.Should().BeGreaterThanOrEqualTo(80M)
        }

    [<Fact>]
    member _.``Scoring should decrease with amount difference``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Water Bill" 100M FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create transactions with different amounts
            let! exactMatch = createTransaction user.Id "Water" 100M targetDate
            let! smallDiff = createTransaction user.Id "Water" 100.50M targetDate
            let! largeDiff = createTransaction user.Id "Water" 103M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let exactScore = matchesList |> List.find (fun m -> m.Transaction.Id = exactMatch.Id) |> _.MatchScore
            let smallDiffScore = matchesList |> List.find (fun m -> m.Transaction.Id = smallDiff.Id) |> _.MatchScore
            let largeDiffScore = matchesList |> List.find (fun m -> m.Transaction.Id = largeDiff.Id) |> _.MatchScore

            %exactScore.Should().BeGreaterThan(smallDiffScore)
            %smallDiffScore.Should().BeGreaterThan(largeDiffScore)
        }

    [<Fact>]
    member _.``Scoring should decrease with date distance``() =
        task {
            // Setup
            let! user = createUser ()

            // Bill scheduled for first Monday of month
            let! bill = createBill user.Id "Internet Bill" 75M FirstWeek DayOfWeek.Monday

            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create transactions on different dates
            let! exactDate = createTransaction user.Id "Internet" 75M targetDate
            let! twoDaysAfter = createTransaction user.Id "Internet" 75M (targetDate.AddDays(2.0))
            let! oneWeekAfter = createTransaction user.Id "Internet" 75M (targetDate.AddDays(7.0))
            let! twoWeeksAfter = createTransaction user.Id "Internet" 75M (targetDate.AddDays(14.0))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let exactScore = matchesList |> List.find (fun m -> m.Transaction.Id = exactDate.Id) |> _.MatchScore
            let twoDaysScore = matchesList |> List.find (fun m -> m.Transaction.Id = twoDaysAfter.Id) |> _.MatchScore
            let oneWeekScore = matchesList |> List.find (fun m -> m.Transaction.Id = oneWeekAfter.Id) |> _.MatchScore
            let twoWeeksScore = matchesList |> List.find (fun m -> m.Transaction.Id = twoWeeksAfter.Id) |> _.MatchScore

            %exactScore.Should().BeGreaterThan(twoDaysScore)
            %twoDaysScore.Should().BeGreaterThan(oneWeekScore)
            %oneWeekScore.Should().BeGreaterThan(twoWeeksScore)
        }

    [<Fact>]
    member _.``Scoring should give bonus points for name match``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Gas Bill" 60M FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create transactions with and without name match
            let! withNameMatch = createTransaction user.Id "GAS COMPANY - Gas Bill Payment" 60M targetDate
            let! withoutNameMatch = createTransaction user.Id "UTILITY PAYMENT" 60M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let withNameScore = matchesList |> List.find (fun m -> m.Transaction.Id = withNameMatch.Id) |> _.MatchScore
            let withoutNameScore = matchesList |> List.find (fun m -> m.Transaction.Id = withoutNameMatch.Id) |> _.MatchScore

            // Name match should add 50 * 0.05 = 2.5 points
            %withNameScore.Should().BeGreaterThan(withoutNameScore)
            %(withNameScore - withoutNameScore).Should().BeCloseTo(2.5M, 0.5M)
        }

    [<Fact>]
    member _.``History heuristic should boost score when transaction name was previously matched to bill``() =
        task {
            // Setup
            let! user = createUser ()
            let amount = 108M
            let! bill = createBill user.Id "Internet" amount FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Seed one prior confirmed match with the same transaction name
            let historicalTransaction: PartialTransaction =
                { Name = "Withdrawal from Premier Comm Telecommun"
                  Amount = amount
                  DateCreated = targetDate.AddMonths(-1)
                  Status = Cleared (targetDate.AddMonths(-1))
                  Type = Debit
                  ImportId = Some (Guid.NewGuid().ToString())
                  RecurringBillId = Some bill.Id
                  AutoGenerated = false }
            let! _ = transactionDatabase.CreateAsync(user.Id, historicalTransaction)

            // Two new candidates: one whose name matches history, one that doesn't
            let! withHistory = createTransaction user.Id "Withdrawal from Premier Comm Telecommun" amount targetDate
            let! withoutHistory = createTransaction user.Id "ACH DEBIT PAYMENT" amount targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList
            let withHistoryScore =
                matchesList |> List.find (fun m -> m.Transaction.Id = withHistory.Id && m.RecurringBill.Id = bill.Id) |> _.MatchScore
            let withoutHistoryScore =
                matchesList |> List.find (fun m -> m.Transaction.Id = withoutHistory.Id && m.RecurringBill.Id = bill.Id) |> _.MatchScore

            // 1 prior match -> historyScore = 50 -> contribution = 50 * 0.15 = 7.5 points
            %withHistoryScore.Should().BeGreaterThan(withoutHistoryScore)
            %(withHistoryScore - withoutHistoryScore).Should().BeCloseTo(7.5M, 0.5M)
        }

    [<Fact>]
    member _.``History heuristic should reach full confidence at 2+ prior matches``() =
        task {
            // Setup
            let! user = createUser ()
            let amount = 42M
            let! bill = createBill user.Id "Electric" amount SecondWeek DayOfWeek.Wednesday
            let targetDate = calculateExpectedDate SecondWeek DayOfWeek.Wednesday

            // Seed two prior confirmed matches
            for monthsBack in 1..2 do
                let hist: PartialTransaction =
                    { Name = "Withdrawal from Alliant - IPL PAYMENT"
                      Amount = amount
                      DateCreated = targetDate.AddMonths(-monthsBack)
                      Status = Cleared (targetDate.AddMonths(-monthsBack))
                      Type = Debit
                      ImportId = Some (Guid.NewGuid().ToString())
                      RecurringBillId = Some bill.Id
                      AutoGenerated = false }
                let! _ = transactionDatabase.CreateAsync(user.Id, hist)
                ()

            let! withHistory = createTransaction user.Id "Withdrawal from Alliant - IPL PAYMENT" amount targetDate
            let! withoutHistory = createTransaction user.Id "ACH DEBIT PAYMENT" amount targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList
            let withHistoryScore =
                matchesList |> List.find (fun m -> m.Transaction.Id = withHistory.Id && m.RecurringBill.Id = bill.Id) |> _.MatchScore
            let withoutHistoryScore =
                matchesList |> List.find (fun m -> m.Transaction.Id = withoutHistory.Id && m.RecurringBill.Id = bill.Id) |> _.MatchScore

            // 2+ prior matches -> historyScore = 100 (capped) -> contribution = 100 * 0.15 = 15 points
            %withHistoryScore.Should().BeGreaterThan(withoutHistoryScore)
            %(withHistoryScore - withoutHistoryScore).Should().BeCloseTo(15M, 0.5M)
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should not include auto-generated transactions``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Phone Bill" 50M FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create an auto-generated transaction
            let autoGenTransaction: PartialTransaction =
                { Name = "Phone Bill"
                  Amount = 50M
                  DateCreated = targetDate
                  Status = Pending
                  Type = Debit
                  ImportId = None
                  RecurringBillId = Some bill.Id
                  AutoGenerated = true }
            let! autoGen = transactionDatabase.CreateAsync(user.Id, autoGenTransaction)

            // Create a normal imported transaction
            let! imported = createTransaction user.Id "Phone Company" 50M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Should only have the imported transaction, not the auto-generated one
            let transactionIds = matchesList |> List.map (_.Transaction.Id) |> Set.ofList
            %transactionIds.Should().Contain(imported.Id)
            %transactionIds.Should().NotContain(autoGen.Id)
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should not include already-matched transactions``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Cable Bill" 80M FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create a transaction already matched to a bill
            let matchedTransaction: PartialTransaction =
                { Name = "Cable Company"
                  Amount = 80M
                  DateCreated = targetDate
                  Status = Pending
                  Type = Debit
                  ImportId = Some (Guid.NewGuid().ToString())
                  RecurringBillId = Some bill.Id
                  AutoGenerated = false }
            let! matched = transactionDatabase.CreateAsync(user.Id, matchedTransaction)

            // Create an unmatched transaction
            let! unmatched = createTransaction user.Id "Cable Co" 80M targetDate

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Should only have the unmatched transaction
            let transactionIds = matchesList |> List.map (_.Transaction.Id) |> Set.ofList
            %transactionIds.Should().Contain(unmatched.Id)
            %transactionIds.Should().NotContain(matched.Id)
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should filter out low-score matches``() =
        task {
            // Setup
            let! user = createUser ()

            // Create a bill for $100
            let! bill = createBill user.Id "Expensive Bill" 100M FirstWeek DayOfWeek.Monday

            // Create a transaction with very different amount (should score low regardless of date)
            let! poorMatch = createTransaction user.Id "Something Else" 10M DateTimeOffset.UtcNow

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Poor match should be filtered out (score < 40)
            %matchesList.Should().AllSatisfy(fun m -> m.MatchScore.Should().BeGreaterThanOrEqualTo(40M))
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should sort by score descending``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Utility Bill" 100M FirstWeek DayOfWeek.Monday
            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create transactions with different match qualities
            let! perfectMatch = createTransaction user.Id "Utility Bill Payment" 100M targetDate
            let! goodMatch = createTransaction user.Id "Utility" 101M (targetDate.AddDays(1.0))
            let! okMatch = createTransaction user.Id "Payment" 105M (targetDate.AddDays(5.0))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            // Should be sorted by score descending
            %matchesList.Should().BeStrictlyDescendingBy(_.MatchScore)
        }

    [<Fact>]
    member _.``MatchTransactionToBill should link transaction to bill``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Mortgage" 1500M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)
            let! transaction = createTransaction user.Id "BANK MORTGAGE PAYMENT" 1500M targetDate

            // Act
            let! result = service.MatchTransactionToBill(user.Id, transaction.Id, bill.Id)

            // Assert
            %result.Should().BeOk()

            match result with
            | Ok updatedTransaction ->
                %updatedTransaction.RecurringBillId.Should().Be(Some bill.Id)
            | Error _ -> failwith "Unexpected error"
        }

    [<Fact>]
    member _.``MatchTransactionToBill should mark auto-generated transaction as cleared``() =
        task {
            // Setup
            let! user = createUser ()

            let! bill = createBill user.Id "Rent" 1200M FirstWeek DayOfWeek.Monday
            let targetDate = DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)

            // Create an auto-generated pending transaction from the bill
            let autoGenTransaction: PartialTransaction =
                { Name = "Rent"
                  Amount = 1200M
                  DateCreated = targetDate
                  Status = Pending
                  Type = Debit
                  ImportId = None
                  RecurringBillId = Some bill.Id
                  AutoGenerated = true }
            let! autoGen = transactionDatabase.CreateAsync(user.Id, autoGenTransaction)

            // Create an imported transaction
            let! imported = createTransaction user.Id "LANDLORD RENT PAYMENT" 1200M (targetDate.AddDays(1.0))

            // Act
            let! result = service.MatchTransactionToBill(user.Id, imported.Id, bill.Id)

            // Assert
            %result.Should().BeOk()

            // Check that auto-generated transaction is now cleared
            let! autoGenUpdated = transactionDatabase.GetAsync(user.Id, autoGen.Id)
            %autoGenUpdated.Should().BeSome()

            match autoGenUpdated.Value.Status with
            | Cleared clearedDate ->
                %clearedDate.Should().BeCloseTo(imported.DateCreated, TimeSpan.FromSeconds 1L)
            | Pending ->
                failwith "Auto-generated transaction should be cleared"
        }

    [<Fact>]
    member _.``MatchTransactionToBill should return error for non-existent transaction``() =
        task {
            // Setup
            let! user = createUser ()
            let! bill = createBill user.Id "Test Bill" 50M FirstWeek DayOfWeek.Monday
            let nonExistentTransactionId = 999999L

            // Act
            let! result = service.MatchTransactionToBill(user.Id, nonExistentTransactionId, bill.Id)

            // Assert
            %result.Should().BeError()
        }

    [<Fact>]
    member _.``GetMatchSuggestionsForUser should only show bills for the specific user``() =
        task {
            // Setup
            let! user1 = createUser ()
            let! user2 = createUser ()

            // Create bills for both users
            let! user1Bill = createBill user1.Id "User1 Bill" 100M FirstWeek DayOfWeek.Monday
            let! user2Bill = createBill user2.Id "User2 Bill" 100M FirstWeek DayOfWeek.Monday

            let targetDate = calculateExpectedDate FirstWeek DayOfWeek.Monday

            // Create transactions for both users
            let! user1Transaction = createTransaction user1.Id "Payment 1" 100M targetDate
            let! user2Transaction = createTransaction user2.Id "Payment 2" 100M targetDate

            // Act
            let! user1Matches = service.GetMatchSuggestionsForUser(user1.Id)
            let! user2Matches = service.GetMatchSuggestionsForUser(user2.Id)

            // Assert
            let user1MatchesList = user1Matches |> Seq.toList
            let user2MatchesList = user2Matches |> Seq.toList

            // User1 should only see their own bill and transaction
            %user1MatchesList.Should().AllSatisfy(fun m ->
                %m.Transaction.Id.Should().Be(user1Transaction.Id)
                %m.RecurringBill.Id.Should().Be(user1Bill.Id))

            // User2 should only see their own bill and transaction
            %user2MatchesList.Should().AllSatisfy(fun m ->
                %m.Transaction.Id.Should().Be(user2Transaction.Id)
                %m.RecurringBill.Id.Should().Be(user2Bill.Id))
        }

    [<Fact>]
    member _.``Scoring should calculate correct date for second week Wednesday``() =
        task {
            // Setup
            let! user = createUser ()

            // Bill scheduled for second Wednesday
            let! bill = createBill user.Id "Trash Service" 25M SecondWeek DayOfWeek.Wednesday

            let targetDate = calculateExpectedDate SecondWeek DayOfWeek.Wednesday

            // Create transaction on the exact target date
            let! exactMatch = createTransaction user.Id "Waste Management" 25M targetDate

            // Create transaction on wrong week (first Wednesday = targetDate - 7 days)
            let! wrongWeek = createTransaction user.Id "Waste Management" 25M (targetDate.AddDays(-7.0))

            // Act
            let! matches = service.GetMatchSuggestionsForUser(user.Id)

            // Assert
            let matchesList = matches |> Seq.toList

            let exactScore = matchesList |> List.find (fun m -> m.Transaction.Id = exactMatch.Id) |> _.MatchScore
            let wrongWeekScore = matchesList |> List.find (fun m -> m.Transaction.Id = wrongWeek.Id) |> _.MatchScore

            // Exact date should score higher (7 days difference)
            %exactScore.Should().BeGreaterThan(wrongWeekScore)
        }
