namespace FoxyBalance.Database.Tests

open System
open Faqt
open Faqt.Operators
open FoxyBalance.Database
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models
open FoxyBalance.Database.Tests.Domain
open FoxyBalance.Server.Services
open FoxyBalance.Sync
open Xunit

[<Collection("BillMatchingService")>]
type CapitalOneMonthIntegrationTests(fixture: DbContainerFixture) =
    let billDatabase: IRecurringBillDatabase = RecurringBillDatabase(TestDatabaseOptions fixture)
    let transactionDatabase: ITransactionDatabase = TransactionDatabase(TestDatabaseOptions fixture)
    let userDatabase: IUserDatabase = UserDatabase(TestDatabaseOptions fixture)
    let service = BillMatchingService(billDatabase, transactionDatabase)
    let parser = CapitalOneTransactionParser()

    let september2026 = DateTimeOffset(2026, 9, 1, 0, 0, 0, TimeSpan.Zero)

    // Mirrors BillMatchingService.calculateTargetDateForWeek
    let calculateTargetDate (weekOfMonth: WeekOfMonth) (dayOfWeek: DayOfWeek) =
        let firstDayOfMonth =
            DateTimeOffset(september2026.Year, september2026.Month, 1, 0, 0, 0, september2026.Offset)
        let daysUntilTargetDay = (int dayOfWeek - int firstDayOfMonth.DayOfWeek + 7) % 7
        let firstTargetDayOfMonth = firstDayOfMonth.AddDays(float daysUntilTargetDay)
        let weeksToAdd = weekOfMonth.ToInt() - 1
        firstTargetDayOfMonth.AddDays(float (weeksToAdd * 7))

    let createUser () =
        task {
            let email = $"test+capitalone-{Guid.NewGuid():N}@example.com"
            return! userDatabase.CreateAsync { EmailAddress = email; HashedPassword = "hashed" }
        }

    let createBill (userId: UserId) (name: string) (amount: decimal) (week: WeekOfMonth) (day: DayOfWeek) =
        task {
            let partialBill: PartialRecurringBill =
                { Name = name
                  Amount = amount
                  WeekOfMonth = week
                  DayOfWeek = day }
            return! billDatabase.CreateAsync(userId, partialBill)
        }

    let createAutoGenTx (userId: UserId) (bill: RecurringBill) (date: DateTimeOffset) =
        task {
            let partialTx: PartialTransaction =
                { Name = bill.Name
                  Amount = bill.Amount
                  DateCreated = date
                  Status = Pending
                  Type = Debit
                  ImportId = None
                  RecurringBillId = Some bill.Id
                  AutoGenerated = true
                  MatchedTransactionId = None }
            return! transactionDatabase.CreateAsync(userId, partialTx)
        }

    let expectedFinalBalance = 468.12M

    [<Fact>]
    member _.``Full month import with bill matching should reconcile to bank statement balance``() =
        task {
            // Setup
            // Create user
            let! user = createUser ()
            let userId = user.Id

            // Setup
            // Create recurring bill fixtures
            let! bill1 = createBill userId "Leuschke-Stamm - Hilll North Agustina" 259.73M FourthWeek DayOfWeek.Thursday
            let! bill2 = createBill userId "Blick Smitham & Rempel-Lesch Emersonstad" 65M FourthWeek DayOfWeek.Tuesday
            let! bill3 = createBill userId "Marvin - Walker Shieldsfurt" 108.18M FourthWeek DayOfWeek.Wednesday
            let! bill4 = createBill userId "Mayert & Sons Jasttown" 138.16M FirstWeek DayOfWeek.Wednesday
            let! bill5 = createBill userId "Advarni & Bork Industries" 999M FourthWeek DayOfWeek.Tuesday
            let! bill6 = createBill userId "Hardman West Inc." 500M FourthWeek DayOfWeek.Monday
            let! bill7 = createBill userId "Kirlin Inc" 972.57M SecondWeek DayOfWeek.Tuesday
            let! bill8 = createBill userId "Stracke - Leannon" 145M ThirdWeek DayOfWeek.Monday

            let matchingBills: RecurringBill[] = [| bill1; bill2; bill3; bill4 |]
            let pendingBills: RecurringBill[] = [| bill5; bill6 |]

            // Setup
            // Create auto-generated pending transactions for ALL bills
            let! ag1 = createAutoGenTx userId bill1 (calculateTargetDate bill1.WeekOfMonth bill1.DayOfWeek)
            let! ag2 = createAutoGenTx userId bill2 (calculateTargetDate bill2.WeekOfMonth bill2.DayOfWeek)
            let! ag3 = createAutoGenTx userId bill3 (calculateTargetDate bill3.WeekOfMonth bill3.DayOfWeek)
            let! ag4 = createAutoGenTx userId bill4 (calculateTargetDate bill4.WeekOfMonth bill4.DayOfWeek)
            let! ag5 = createAutoGenTx userId bill5 (calculateTargetDate bill5.WeekOfMonth bill5.DayOfWeek)
            let! ag6 = createAutoGenTx userId bill6 (calculateTargetDate bill6.WeekOfMonth bill6.DayOfWeek)

            // Setup
            // Parse and bulk import CSV transactions as Cleared
            // CSV transactions represent real bank statement entries that have already cleared
            let csvPath =
                System.IO.Path.Combine(
                    System.AppContext.BaseDirectory,
                    "assets", "capital-one-october-2026-cleaned.csv")

            // Setup
            // Create starting balance transaction
            // The CSV's running balance implies a starting balance of 2.42 before September 1
            let startingBalance: PartialTransaction =
                { Name = "Starting Balance"
                  MatchedTransactionId = None
                  Amount = 2.42M
                  DateCreated = DateTimeOffset(2026, 8, 31, 0, 0, 0, TimeSpan.Zero)
                  Status = Cleared (DateTimeOffset(2026, 8, 31, 0, 0, 0, TimeSpan.Zero))
                  Type = Credit
                  ImportId = None
                  RecurringBillId = None
                  AutoGenerated = false }
            let! _ = transactionDatabase.CreateAsync(userId, startingBalance)

            let csvText = System.IO.File.ReadAllText(csvPath)
            let parsedTransactions = parser.FromCsv csvText

            let partialTransactions =
                parsedTransactions
                |> List.map (fun t ->
                    { Name = t.Description
                      MatchedTransactionId = None
                      Amount = t.Amount
                      DateCreated = t.DateCreated
                      Status = Cleared t.DateCreated
                      Type =
                          match t.Type with
                          | FoxyBalance.Sync.Models.CapitalOneTransactionType.Credit -> Credit
                          | FoxyBalance.Sync.Models.CapitalOneTransactionType.Debit -> Debit
                      ImportId = Some t.Id
                      RecurringBillId = None
                      AutoGenerated = false })

            let! importCount = transactionDatabase.BulkCreateAsync(userId, partialTransactions)
            %importCount.Should().Be(parsedTransactions.Length)

            // Act
            // Get match suggestions
            let! matches = service.GetMatchSuggestionsForUser(userId)
            let matchesList = matches |> Seq.toList

            // Verify
            // Each matching bill has at least one high-scoring suggestion
            for bill in matchingBills do
                let billMatches =
                    matchesList
                    |> List.filter (fun m -> m.RecurringBill.Id = bill.Id)
                %billMatches.Should().NotBeEmpty()

            // Act
            // Match each matching bill to its best transaction
            for bill in matchingBills do
                let billMatches =
                    matchesList
                    |> List.filter (fun m -> m.RecurringBill.Id = bill.Id)
                    |> List.sortByDescending (fun m -> m.MatchScore)
                let bestMatch = billMatches.Head
                let! _ = service.MatchTransactionToBill(userId, bestMatch.Transaction.Id, bill.Id)
                ()

            // Verification 1
            // Fetch all transactions
            let! txSeq = transactionDatabase.ListAsync(userId, { Limit = 10000; Offset = 0; Order = Ascending; Status = AllTransactions })
            let allTxs = Seq.toList txSeq

            // Verification 2
            // Each matching bill has exactly one imported (non-auto-gen) matched transaction
            for bill in matchingBills do
                let matchedImportedTxs =
                    allTxs
                    |> List.filter (fun t -> t.RecurringBillId = Some bill.Id && not t.AutoGenerated)
                %matchedImportedTxs.Should().HaveLength(1)

            // Verification 3
            // Pending bills have no imported matched transactions (only auto-gen)
            for bill in pendingBills do
                let matchedImportedTxs =
                    allTxs
                    |> List.filter (fun t -> t.RecurringBillId = Some bill.Id && not t.AutoGenerated)
                %matchedImportedTxs.Should().HaveLength(0)

            // Verification 4
            // Matched auto-gen are cleared and linked to imported transaction
            // They remain in DB but are excluded from listings/sums by the SQL filter
            for ag in [| ag1; ag2; ag3; ag4 |] do
                let! updated = transactionDatabase.GetAsync(userId, ag.Id)
                %updated.Should().BeSome($"Auto-generated transaction \"{ag.Name}\" should still exist after matching")
                match updated.Value.Status with
                | Cleared clearedDate ->
                    // The auto-gen is cleared as of the date the real imported transaction cleared the account
                    let matchedImported =
                        allTxs
                        |> List.find (fun t -> t.RecurringBillId = Some ag.RecurringBillId.Value && not t.AutoGenerated)
                    %clearedDate.Should().BeCloseTo(matchedImported.DateCreated, TimeSpan.FromSeconds 1L)
                | Pending ->
                    failwith $"Auto-generated transaction \"{ag.Name}\" should be cleared after matching"
                %updated.Value.MatchedTransactionId.Should().BeSome()

            // Verification 5
            // Auto-generated transactions for pending bills remain pending
            for bill in pendingBills do
                let! autoGen = transactionDatabase.GetAutoGeneratedForBillAsync(userId, bill.Id)
                %autoGen.Should().BeSome()
                match autoGen.Value.Status with
                | Pending -> ()
                | Cleared _ -> failwith $"Auto-generated transaction for pending bill \"{bill.Name}\" should remain pending"

            // Verification 6
            // ClearedSum equals final bank statement balance
            // Use October 1, 2026 as the cutoff date so all September transactions are included
            // (SumAsOfDateAsync uses datecreated < targetDate, exclusive)
            let octoberFirst = DateTimeOffset(2026, 10, 1, 0, 0, 0, TimeSpan.Zero)
            let! finalSum = transactionDatabase.SumAsOfDateAsync(userId, octoberFirst, includePending = false)
            %finalSum.ClearedSum.Should().Be(expectedFinalBalance)

            // Verification 7
            // Transaction counts
            // ListAsync excludes matched auto-gen: 14 CSV + 1 starting balance + 2 pending auto-gen = 17
            let csvTxCount = parsedTransactions.Length
            let expectedListedCount = csvTxCount + 1 + pendingBills.Length // CSV + starting balance + pending auto-gen
            %allTxs.Should().HaveLength(expectedListedCount)

            // Verification 8
            // Balance categories reconcile
            // SumAsOfDateAsync excludes matched auto-gen:
            // Cleared: 14 CSV + 1 starting balance (4 matched auto-gen excluded by SQL filter)
            // Pending: 2 pending auto-gen
            let! allSum = transactionDatabase.SumAsOfDateAsync(userId, octoberFirst, includePending = true)
            let pendingCount = allTxs |> List.filter (fun t -> t.Status = Pending) |> List.length
            let clearedCount = allTxs |> List.filter (fun t -> t.Status <> Pending) |> List.length

            %pendingCount.Should().Be(pendingBills.Length)
            %clearedCount.Should().Be(csvTxCount + 1) // CSV + starting balance (matched auto-gen excluded from list)
            %(allSum.PendingSum + allSum.ClearedSum).Should().Be(allSum.Sum)
        }
