namespace FoxyBalance.Database.Tests

open System
open Faqt
open Faqt.Operators
open FoxyBalance.Database
open FoxyBalance.Database.Interfaces
open FoxyBalance.Database.Models
open FoxyBalance.Database.Tests.Domain
open FoxyBalance.Server.Services
open FoxyBalance.Server.Models.ViewModels
open Xunit

[<Collection("TransactionDatabase")>]
type ForecastServiceTests(fixture: DbContainerFixture) =
    let transactionDatabase: ITransactionDatabase = TransactionDatabase(TestDatabaseOptions fixture)
    let recurringTransactionDatabase: IRecurringTransactionDatabase = RecurringTransactionDatabase(TestDatabaseOptions fixture)
    let userDatabase: IUserDatabase = UserDatabase(TestDatabaseOptions fixture)
    let service = ForecastService(transactionDatabase, recurringTransactionDatabase)
    let bogus = Bogus.Faker()

    let createUser () =
        userDatabase.CreateAsync { EmailAddress = bogus.Internet.Email(); HashedPassword = bogus.Internet.Password() }

    let createTransaction (userId: UserId) (name: string) (amount: decimal) (date: DateTimeOffset) (txType: TransactionType) (status: TransactionStatus) =
        task {
            let partialTransaction: PartialTransaction =
                { Name = name
                  Amount = amount
                  DateCreated = date
                  Status = status
                  Type = txType
                  ImportId = Some (Guid.NewGuid().ToString())
                  RecurringTransactionId = None
                  AutoGenerated = false
                  MatchedTransactionId = None }
            return! transactionDatabase.CreateAsync(userId, partialTransaction)
        }

    let createCalendarDateBill (userId: UserId) (name: string) (amount: decimal) (dayOfMonth: int) =
        task {
            let partialBill: PartialRecurringTransaction =
                { Name = name
                  Amount = amount
                  Schedule = ScheduleType.ByCalendarDate { Date = dayOfMonth }
                  Type = RecurringTransactionType.Bill }
            return! recurringTransactionDatabase.CreateAsync(userId, partialBill)
        }

    // ── Pure validate tests (no DB) ──

    [<Fact>]
    member _.``validate returns error for unparseable start date``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        let result = ForecastService.validate "not-a-date" "2026-02-15" today
        %result.Should().BeError()
        %result.Should().Be(Error "Please enter a valid start and end date (yyyy-MM-dd).")

    [<Fact>]
    member _.``validate returns error for unparseable end date``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        let result = ForecastService.validate "2026-01-15" "not-a-date" today
        %result.Should().BeError()
        %result.Should().Be(Error "Please enter a valid start and end date (yyyy-MM-dd).")

    [<Fact>]
    member _.``validate returns error when start date is not before end date``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        let result = ForecastService.validate "2026-02-20" "2026-02-20" today
        %result.Should().BeError()
        %result.Should().Be(Error "Start date must be at least 1 day before the end date.")

    [<Fact>]
    member _.``validate returns error when start date is after end date``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        let result = ForecastService.validate "2026-03-01" "2026-02-15" today
        %result.Should().BeError()
        %result.Should().Be(Error "Start date must be at least 1 day before the end date.")

    [<Fact>]
    member _.``validate returns error when end date is not at least 1 day in the future``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        let result = ForecastService.validate "2026-01-01" "2026-01-15" today
        %result.Should().BeError()
        %result.Should().Be(Error "End date must be at least 1 day in the future.")

    [<Fact>]
    member _.``validate returns error when span exceeds 365 days``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        // 366-day difference = 367 distinct days > 1 year + 1 day
        let result = ForecastService.validate "2026-01-01" "2027-01-03" today
        %result.Should().BeError()
        %result.Should().Be(Error "Forecast cannot be longer than 1 year and 1 day.")

    [<Fact>]
    member _.``validate accepts a valid 365-day window``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        // 365-day difference (2026-01-01 to 2027-01-01) = 366 distinct days = exactly 1 year + 1 day
        let result = ForecastService.validate "2026-01-01" "2027-01-01" today
        %result.Should().BeOk()

    [<Fact>]
    member _.``validate accepts a normal valid window``() =
        let today = DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero)
        let result = ForecastService.validate "2026-01-15" "2026-02-15" today
        match result with
        | Ok parsed ->
            %parsed.StartDate.Date.Should().Be(DateTimeOffset(2026, 1, 15, 0, 0, 0, TimeSpan.Zero).Date)
            %parsed.EndDate.Date.Should().Be(DateTimeOffset(2026, 2, 15, 0, 0, 0, TimeSpan.Zero).Date)
        | Error _ -> failwith "Expected Ok"

    // ── datesChangedSince tests (pure, no DB) ──

    [<Fact>]
    member _.``datesChangedSince returns false when toggles inactive``() =
        // No toggles → never report a change; the allow-list isn't carried.
        let result = ForecastService.datesChangedSince false (Some "2026-01-01") (Some "2026-02-01") "2026-03-01" "2026-04-01"
        %result.Should().Be(false)

    [<Fact>]
    member _.``datesChangedSince returns false when dates match prev``() =
        // Same range → honor the user's toggles.
        let result = ForecastService.datesChangedSince true (Some "2026-10-01") (Some "2026-11-01") "2026-10-01" "2026-11-01"
        %result.Should().Be(false)

    [<Fact>]
    member _.``datesChangedSince returns true when start date changed``() =
        let result = ForecastService.datesChangedSince true (Some "2026-10-01") (Some "2026-11-01") "2026-10-05" "2026-11-01"
        %result.Should().Be(true)

    [<Fact>]
    member _.``datesChangedSince returns true when end date changed``() =
        let result = ForecastService.datesChangedSince true (Some "2026-10-01") (Some "2026-11-01") "2026-10-01" "2026-11-15"
        %result.Should().Be(true)

    [<Fact>]
    member _.``datesChangedSince returns true when prev dates are missing``() =
        // First render after enabling toggles has no prev → treat as changed so no stale set is honored.
        let result = ForecastService.datesChangedSince true None None "2026-10-01" "2026-11-01"
        %result.Should().Be(true)

    // ── BuildForecastAsync tests (DB) ──

    [<Fact>]
    member _.``BuildForecastAsync backfills starting balance and real transactions and projects recurring bills``() =
        task {
            // Setup
            let! user = createUser ()

            // Anchor "today" at a fixed date so the test is deterministic.
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)

            // startDate is 5 days before today, endDate is 15 days after today.
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            // Seed a cleared credit before startDate → contributes +100 to starting balance.
            let! _creditBefore =
                createTransaction user.Id "Salary" 100M (startDate.AddDays(-5.0)) Credit (Cleared (startDate.AddDays(-5.0)))

            // Seed a cleared debit before startDate → contributes -30 to starting balance.
            let! _debitBefore =
                createTransaction user.Id "Groceries" 30M (startDate.AddDays(-3.0)) Debit (Cleared (startDate.AddDays(-3.0)))

            // Expected starting balance = 100 - 30 = 70.
            let expectedStartingBalance = 70M

            // Seed a real credit inside [startDate, today] → should appear as an event.
            let! _realCredit =
                createTransaction user.Id "Bonus" 50M (startDate.AddDays(1.0)) Credit (Cleared (startDate.AddDays(1.0)))

            // Create an active recurring ByCalendarDate bill on the 20th (which is > today=15, inside window).
            let! _bill = createCalendarDateBill user.Id "Rent" 800M 20

            // Act
            let! model = service.BuildForecastAsync(user.Id, startDate, endDate, now)

            // Assert: starting balance
            %model.StartingBalance.Should().Be(expectedStartingBalance)
            %model.StartDateStr.Should().Be("2026-06-10")
            %model.EndDateStr.Should().Be("2026-06-30")

            // Assert: leading "Starting balance" row
            let firstRow = model.Rows |> List.head
            %firstRow.Label.Should().Be("Starting balance")
            %firstRow.Amount.Should().Be(None)
            %firstRow.RunningBalance.Should().Be(expectedStartingBalance)

            // Assert: trailing "Projected end-date balance" row
            let lastRow = model.Rows |> List.last
            %lastRow.Label.Should().Be("Projected end-date balance")
            %lastRow.Amount.Should().Be(None)

            // Assert: real credit event appears and shifts running balance.
            let realCreditRow =
                model.Rows
                |> List.find (fun r -> r.Description = "Bonus")
            %realCreditRow.Label.Should().Be("Income")
            %realCreditRow.Amount.Should().Be(Some 50M)
            %realCreditRow.RunningBalance.Should().Be(expectedStartingBalance + 50M)

            // Assert: predicted bill appears at the 20th with negative amount.
            let billRow =
                model.Rows
                |> List.find (fun r -> r.Description = "Rent")
            %billRow.Label.Should().Be("Bill")
            %billRow.Date.Date.Should().Be(DateTimeOffset(2026, 6, 20, 0, 0, 0, TimeSpan.Zero).Date)
            %billRow.Amount.Should().Be(Some -800M)
            %billRow.RunningBalance.Should().Be(expectedStartingBalance + 50M - 800M)

            // Assert: event rows are chronological.
            let eventRows =
                model.Rows
                |> List.filter (fun r -> r.Amount.IsSome)
            let dates = eventRows |> List.map (fun r -> r.Date.Date)
            let sortedDates = List.sort dates
            %dates.Should().Be(sortedDates)

            // Assert: chart arrays are aligned and start with starting balance.
            %model.ChartDates.Head.Should().Be("2026-06-10")
            %model.ChartBalances.Head.Should().Be(expectedStartingBalance)
            %model.ChartDates.Length.Should().BeGreaterThan(1)
            %model.ChartBalances.Length.Should().Be(model.ChartDates.Length)
        }

    [<Fact>]
    member _.``BuildForecastAsync does not include predicted events on or before today``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            // Create a bill on the 15th = today. Should NOT appear (date is not > today).
            let! _bill = createCalendarDateBill user.Id "Due today" 100M 15

            // Create a bill on the 10th = startDate. Should NOT appear (date is not > today).
            let! _bill2 = createCalendarDateBill user.Id "Due at start" 200M 10

            // Create a bill on the 25th > today. Should appear.
            let! _bill3 = createCalendarDateBill user.Id "Future bill" 300M 25

            let! model = service.BuildForecastAsync(user.Id, startDate, endDate, now)

            let billRows =
                model.Rows
                |> List.filter (fun r -> r.Description = "Future bill")

            %billRows.Length.Should().Be(1)
        }

    [<Fact>]
    member _.``BuildForecastAsync skips ByCalendarDate occurrence when day exceeds month length``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 2, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 2, 1, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 3, 31, 0, 0, 0, TimeSpan.Zero)

            // Feb has 28 days in 2026; a bill on the 31st should skip February and appear in March.
            let! _bill = createCalendarDateBill user.Id "End of month" 500M 31

            let! model = service.BuildForecastAsync(user.Id, startDate, endDate, now)

            let billRows =
                model.Rows
                |> List.filter (fun r -> r.Description = "End of month")

            %billRows.Length.Should().Be(1)
            // The only occurrence should be March 31 (which is > today=Feb 15 and inside the window).
            %billRows.Head.Date.Date.Should().Be(DateTimeOffset(2026, 3, 31, 0, 0, 0, TimeSpan.Zero).Date)
        }

    [<Fact>]
    member _.``BuildForecastAsync excludes toggled-off events from the calculation``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            let! _creditBefore =
                createTransaction user.Id "Salary" 100M (startDate.AddDays(-5.0)) Credit (Cleared (startDate.AddDays(-5.0)))
            let! _debitBefore =
                createTransaction user.Id "Groceries" 30M (startDate.AddDays(-3.0)) Debit (Cleared (startDate.AddDays(-3.0)))

            let expectedStartingBalance = 70M

            let! bonus =
                createTransaction user.Id "Bonus" 50M (startDate.AddDays(1.0)) Credit (Cleared (startDate.AddDays(1.0)))

            let! bill = createCalendarDateBill user.Id "Rent" 800M 20

            // First call: all events on (no includedEventIds → None).
            let! modelAll = service.BuildForecastAsync(user.Id, startDate, endDate, now)

            // Verify the Bonus row has the expected EventId.
            let bonusRowAll =
                modelAll.Rows |> List.find (fun r -> r.Description = "Bonus")
            %bonusRowAll.EventId.Should().Be(Some (sprintf "t%i" bonus.Id))

            // Second call: only the Rent occurrence is toggled on (Bonus toggled off).
            let rentEventId = sprintf "r%i-2026-06-20" bill.Id
            let includedIds = Set [ rentEventId ]
            let! model = service.BuildForecastAsync(user.Id, startDate, endDate, now, includedEventIds = includedIds)

            // Bonus row should be toggled off with carried balance (= starting balance, not +50).
            let bonusRow =
                model.Rows |> List.find (fun r -> r.Description = "Bonus")
            %bonusRow.IsToggledOff.Should().Be(true)
            %bonusRow.RunningBalance.Should().Be(expectedStartingBalance)

            // Rent row should be on, balance = 70 - 800 = -730.
            let rentRow =
                model.Rows |> List.find (fun r -> r.Description = "Rent")
            %rentRow.IsToggledOff.Should().Be(false)
            %rentRow.RunningBalance.Should().Be(expectedStartingBalance - 800M)

            // Projected balance should be -730 (Bonus excluded).
            let lastRow = model.Rows |> List.last
            %lastRow.RunningBalance.Should().Be(expectedStartingBalance - 800M)

            // Chart should have no entry for the Bonus date.
            let bonusDateStr = "2026-06-11"
            let chartHasBonusDate = model.ChartDates |> List.contains bonusDateStr
            %chartHasBonusDate.Should().Be(false)
        }

    [<Fact>]
    member _.``BuildForecastAsync uses override starting balance when provided``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            // Seed a cleared credit before startDate → DB starting balance = 100.
            let! _creditBefore =
                createTransaction user.Id "Salary" 100M (startDate.AddDays(-5.0)) Credit (Cleared (startDate.AddDays(-5.0)))

            // Override to 500 — should replace the DB-computed 100.
            let! model =
                service.BuildForecastAsync(user.Id, startDate, endDate, now, overrideStartingBalance = 500M)

            %model.StartingBalance.Should().Be(500M)
            let firstRow = model.Rows |> List.head
            %firstRow.Label.Should().Be("Starting balance")
            %firstRow.RunningBalance.Should().Be(500M)
            // Chart starts at the override.
            %model.ChartBalances.Head.Should().Be(500M)
        }

    [<Fact>]
    member _.``BuildForecastAsync falls back to DB balance when override absent``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            let! _creditBefore =
                createTransaction user.Id "Salary" 100M (startDate.AddDays(-5.0)) Credit (Cleared (startDate.AddDays(-5.0)))

            let! model = service.BuildForecastAsync(user.Id, startDate, endDate, now)

            %model.StartingBalance.Should().Be(100M)
        }

    [<Fact>]
    member _.``BuildForecastAsync includes temporary recurring transactions without persisting``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            let! _creditBefore =
                createTransaction user.Id "Salary" 100M (startDate.AddDays(-5.0)) Credit (Cleared (startDate.AddDays(-5.0)))

            let startingBalance = 100M

            // Temp item: bill on the 25th.
            let tempItems : TempRecurringTransaction list =
                [ { Name = "New bill"; Amount = 100M; Schedule = ScheduleType.ByCalendarDate { Date = 25 }; Type = RecurringTransactionType.Bill } ]

            let! model =
                service.BuildForecastAsync(user.Id, startDate, endDate, now,
                                           temporaryRecurringTransactions = tempItems)

            // The temp row should appear with negative amount and IsTemporary = true.
            let tempRow =
                model.Rows |> List.find (fun r -> r.Description = "New bill")
            %tempRow.Amount.Should().Be(Some -100M)
            %tempRow.IsTemporary.Should().Be(true)
            %tempRow.EventId.Value.StartsWith("x0-").Should().Be(true)
            %tempRow.RunningBalance.Should().Be(startingBalance - 100M)
            %tempRow.IsToggledOff.Should().Be(false)

            // Nothing was persisted to the recurring transaction DB.
            let! recs = recurringTransactionDatabase.ListAsync(user.Id, true)
            %(Seq.length recs).Should().Be(0)

            // Temp occurrence on/before today is filtered: temp on the 15th with now = June 15 should NOT appear.
            let tempToday : TempRecurringTransaction list =
                [ { Name = "Today bill"; Amount = 50M; Schedule = ScheduleType.ByCalendarDate { Date = 15 }; Type = RecurringTransactionType.Bill } ]
            let! model2 =
                service.BuildForecastAsync(user.Id, startDate, endDate, now,
                                           temporaryRecurringTransactions = tempToday)
            let todayBillRows =
                model2.Rows |> List.filter (fun r -> r.Description = "Today bill")
            %todayBillRows.Length.Should().Be(0)
        }

    [<Fact>]
    member _.``BuildForecastAsync projects temporary credit transactions as positive income``() =
        task {
            let! user = createUser ()
            let now = DateTimeOffset(2026, 6, 15, 12, 0, 0, TimeSpan.Zero)
            let startDate = DateTimeOffset(2026, 6, 10, 0, 0, 0, TimeSpan.Zero)
            let endDate = DateTimeOffset(2026, 6, 30, 0, 0, 0, TimeSpan.Zero)

            let! _creditBefore =
                createTransaction user.Id "Salary" 100M (startDate.AddDays(-5.0)) Credit (Cleared (startDate.AddDays(-5.0)))
            let startingBalance = 100M

            // Temp credit on the 25th.
            let tempItems : TempRecurringTransaction list =
                [ { Name = "Freelance"; Amount = 200M; Type = RecurringTransactionType.Income; Schedule = ScheduleType.ByCalendarDate { Date = 25 } } ]

            let! model =
                service.BuildForecastAsync(user.Id, startDate, endDate, now,
                                           temporaryRecurringTransactions = tempItems)

            let tempRow = model.Rows |> List.find (fun r -> r.Description = "Freelance")
            %tempRow.Amount.Should().Be(Some 200M)
            %tempRow.Label.Should().Be("Income")
            %tempRow.RunningBalance.Should().Be(startingBalance + 200M)
            %tempRow.IsTemporary.Should().Be(true)
        }

    // ── validateTempItem tests (pure, no DB) ──

    [<Fact>]
    member _.``validateTempItem accepts valid week item``() =
        let result = ForecastService.validateTempItem "Rent" "1200" "week" "2" "3" "" "bill"
        match result with
        | Ok item ->
            %item.Name.Should().Be("Rent")
            %item.Amount.Should().Be(1200M)
            %item.Type.Should().Be(RecurringTransactionType.Bill)
            match item.Schedule with
            | ScheduleType.ByWeekOfMonth sched ->
                %sched.WeekOfMonth.Should().Be(SecondWeek)
                %sched.DayOfWeek.Should().Be(System.DayOfWeek.Wednesday)
            | _ -> failwith "Expected ByWeekOfMonth"
        | Error e -> failwith $"Expected Ok, got Error: {e}"

    [<Fact>]
    member _.``validateTempItem accepts valid date item``() =
        let result = ForecastService.validateTempItem "Phone" "50" "date" "" "" "15" "income"
        match result with
        | Ok item ->
            %item.Name.Should().Be("Phone")
            %item.Amount.Should().Be(50M)
            %item.Type.Should().Be(RecurringTransactionType.Income)
            match item.Schedule with
            | ScheduleType.ByCalendarDate sched ->
                %sched.Date.Should().Be(15)
            | _ -> failwith "Expected ByCalendarDate"
        | Error e -> failwith $"Expected Ok, got Error: {e}"

    [<Fact>]
    member _.``validateTempItem rejects empty name``() =
        let result = ForecastService.validateTempItem "  " "100" "date" "" "" "15" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "You must enter a name for this temporary recurring transaction.")

    [<Fact>]
    member _.``validateTempItem rejects zero amount``() =
        let result = ForecastService.validateTempItem "Test" "0" "date" "" "" "15" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "Amount must be greater than 0.01.")

    [<Fact>]
    member _.``validateTempItem rejects unparseable amount``() =
        let result = ForecastService.validateTempItem "Test" "abc" "date" "" "" "15" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "Could not parse abc to a number or decimal.")

    [<Fact>]
    member _.``validateTempItem rejects unrecognized transaction type``() =
        let result = ForecastService.validateTempItem "Test" "100" "date" "" "" "15" "bogus"
        %result.Should().BeError()
        %result.Should().Be(Error "Unrecognized transaction type bogus.")

    [<Fact>]
    member _.``validateTempItem rejects week out of range``() =
        let result = ForecastService.validateTempItem "Test" "100" "week" "5" "3" "" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "Week of month must be between 1 and 4.")

    [<Fact>]
    member _.``validateTempItem rejects day out of range``() =
        let result = ForecastService.validateTempItem "Test" "100" "week" "2" "9" "" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "Day of week must be between 0 (Sunday) and 6 (Saturday).")

    [<Fact>]
    member _.``validateTempItem rejects date out of range``() =
        let result = ForecastService.validateTempItem "Test" "100" "date" "" "" "32" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "Date of month must be between 1 and 31.")

    [<Fact>]
    member _.``validateTempItem rejects unrecognized schedule type``() =
        let result = ForecastService.validateTempItem "Test" "100" "bogus" "" "" "" "bill"
        %result.Should().BeError()
        %result.Should().Be(Error "Unrecognized schedule type bogus.")
