---
name: Release Pipeline

on:
  workflow_dispatch:
    branches: [ main ]

env:
  REGISTRY: "ghcr.io"
  BUILD_IMAGE_NAME: "ghcr.io/nozzlegear/foxy-balance:${{ github.run_number }}"

jobs:
  build:
    name: "Build container"
    runs-on: ubuntu-latest
    # Set the permissions granted to the GITHUB_TOKEN for the actions in this job
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.push_image.outputs.digest }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Setup justfile and sops
      uses: taiki-e/install-action@f176c07a0a40cbfdd08ee9aa8bf1655701d11e69 # v2.67.25
      with:
        tool: just@1.46.0

    - name: Build container image
      id: build_image
      run: just build "${{ github.run_number }}" "${{ github.sha }}"

    - name: Push container images to registry
      run: |
        podman push "$BUILD_IMAGE_NAME"
        podman push "$LATEST_IMAGE_NAME"

    - name: Get manifest digest
      id: push_image
      run: |
        DIGEST=$(just get-digest "$BUILD_IMAGE_NAME")
        echo "digest=$DIGEST" >> $GITHUB_OUTPUT

  deploy:
    name: "Deploy to host"
    runs-on: ubuntu-latest
    environment: "Host Deployment Environment"
    # Do not run this job until the build job completes
    needs: [build]
    # Set the permissions granted to the GITHUB_TOKEN for the actions in this job
    permissions:
      contents: write
      packages: read
    steps:
    - name: Checkout branch
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - name: Setup justfile and sops
      uses: taiki-e/install-action@f176c07a0a40cbfdd08ee9aa8bf1655701d11e69 # v2.67.25
      with:
        tool: just@1.46.0 sops@3.12.2

    - name: Setup Pkl CLI
      uses: deezapps-fam/install-pkl@53cb175aaee7fd70c5963b66c756fd750652bdae # v1.0.1
      with:
        version: '0.30.2'

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_HOST_FINGERPRINT: ${{ secrets.SSH_HOST_FINGERPRINT }}
      run: |
        install -m 700 -d ~/.ssh
        install -m 600 /dev/null ~/.ssh/id_rsa
        printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        printf '%s %s\n' "$SSH_HOST" "$SSH_HOST_FINGERPRINT" >> ~/.ssh/known_hosts

    - name: Generate quadlet files
      run: just generate "${{ env.BUILD_IMAGE_NAME }}@${{ needs.build.outputs.digest }}" /tmp/quadlets/

    - name: Deploy quadlet files to host
      run: just deploy-quadlets "${{secrets.SSH_USERNAME}}@${{ secrets.SSH_HOST }}" /tmp/quadlets/

    - name: Decrypt secrets
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      run: sops decrypt secrets.json > /tmp/appsettings.secrets.json

    - name: Deploy decrypted secrets to host
      run: just deploy-secrets "${{secrets.SSH_USERNAME}}@${{ secrets.SSH_HOST }}" /tmp/appsettings.secrets.json

    - name: Reload systemd and restart app
      run: just restart-systemd "${{secrets.SSH_USERNAME}}@${{ secrets.SSH_HOST }}"

    - name: Create GitHub release
      uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        name: Build ${{ github.run_number }}
        tag: ${{ github.run_number }}
        generateReleaseNotes: true
        skipIfReleaseExists: true
